### ISSUE TITLE
Ability to specify output directory for recorded mapping/files

### ISSUE THREAD

**Issue by unscene** [wiremock/wiremock#1]
This is more of a feature request.  But it would be nice to be able to specify sub directories for recorded files both the generated mapping & __files.  

Example:

```
java -jar wiremock.jar --record-mappings --mappings-dir=somedir  --files-dir=somedir
```

Allows for really easy organization when only trying to record variations of a specific endpoint.

**Comment by handstandsam** [comment]
Sounds cool :-)  Doing this locally now by just creating different subdirectories with __files and mappings in to accomplish the same sorta thing, just have to move the WireMock standalone jar which is a little annoying.

**Comment by handstandsam** [comment]
I jumped the gun, just found --root-dir in the documentation: http://wiremock.org/running-standalone.html

Does this also work for recording, or just playback?

**Comment by tomakehurst** [comment]
Should be both, if memory serves.

**Comment by handstandsam** [comment]
You're right, they both work!  How did I not figure out this until today?  Thanks Tom, this will make things a lot easier.

**Comment by nareshk-gs** [comment]
Is this feature available now...?

I tried `java -jar wiremock-standalone-2.10.1.jar --proxy-all="http://myhost.com" --record-mappings --scenario="successful"` and wiremock fails to start with below exception -

`Exception in thread "main" joptsimple.UnrecognizedOptionException: scenario is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at com.github.tomakehurst.wiremock.standalone.CommandLineOptions.<init>(CommandLineOptions.java:135)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:52)
	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:113)`

**Comment by tomakehurst** [comment]
Not really sure what you're trying to do here, but there's never been any plan to add a `successful` CLI parameter. I'd also suggest trying the new record feature as you're using the legacy one there which is less flexible.

**Comment by handstandsam** [comment]
Use the `root-dir` command line param to use files and mappings in another directory.

**Comment by nareshk-gs** [comment]
That sort of helped. Thanks.
Does WireMock support driving responses based on "x-Correlation-Id" ..?

**Comment by nareshk-gs** [comment]
This worked great for my need. Thanks a bunch!!! I might sound silly, but one last thing for a dummy like me.
I have mapping for multiple services on same folder and different service returns its own response based on the correlation id. I want to have a separate file for each service, that returns a specific response when the predefined correlation IDs doesn't match. A detailed example below.

map "app1-corId1" returns file "app1-corId1" as response on matching corId1 and url
map "app1-corId2" returns file "app1-corId2" as response on matching corId2 and url
map "app2-corId3" returns file "app2-corId3" as response on matching corId3 and url
map "app2-corId4" returns file "app2-corId4" as response on matching corId4 and url

I want to return file "app1-anyCorId" on matching the url on corId mismatch and no corId cases. I tried by adding priority 10 and removing header matching from request, but it fails to bring up the mock service. Is there a way to achieve this...?

**Comment by bharath-holla** [comment]
Hi Tom, 
I have a question regarding placement of wiremock standalone folder in a unix box. Which folder do I place this so that I can test the stubs from a browser or postman?
