### ISSUE TITLE
how to call webservice using wiremock

### ISSUE THREAD

**Issue by lbrd** [wiremock/wiremock#102]
Hi ,

I am new to wire mock, I have written very simple Spring Rest webservice and I want to use wiremock to call this service instead my controler, can you help how can I modify code to make sure, I use wiremock. its very simple code as follow, 

@Controller
@RequestMapping("/state")
public class StateController {

```
@RequestMapping(value = "/{code}", method = RequestMethod.GET)
public  @ResponseBody String getState(@PathVariable String code) {
    String result;
    if (code.equals("KL")) {
        result = "Kerala";
    } else if (code.equals("GJ")){
        result = "Gujarat";
    } else{
        result = "Default State";
    }
    return result;
}
```

urgent help appreciated!!!

Regards,
Lirin.

**Comment by simranj** [comment]
Hi Tom,

I am trying to post data to Wire mock using Rest Assured POST API. 
Rest Assured Syntax:  given().contentType("application/json").and().body("Your_body_here").when().post("http://some_url");

Will something like this work:
given().when().body(requestBody).post(url).contentType("application/json");
or should i write a wrapper over Rest Asssured POST call to integrate with Wire Post. 
Something like this:
 public static void postToWireMock(String url,String requestBody,int responseCode){
          stubFor(WireMock.get(urlEqualTo(url))
                .withHeader("Accept", equalTo("application/json"))
                .willReturn(aResponse()
                        .withStatus(responseCode)
                        .withHeader("Content-Type", "application/json")
                        .withBody(requestBody)));
        given().when().body(requestBody).post(url);

**Comment by vayalaivadivel** [comment]
Hi Tom, Very interesting. Can we have any sample to test SOAP client using Wire Mock with soap request and soap response xml
