### ISSUE TITLE
Not able to register JavaTimeModule on latest version of Wiremock

### ISSUE THREAD

**Issue by gagang123** [wiremock/wiremock#1127]
I  tried to upgrade the Wiremock dependency to the latest one but after upgrading it, there's one complier issue.

In Spring Cloud Contract Wiremock » 1.1.5.RELEASE  version
When I register java Time module in the Json.getObjectMapper().registerModule(New JavaTimeModule()) it works.
In this version I checked the of **getObjectMapper()** is of **com.fasterxml.jackson.databind.ObjectMapper** type.

In Spring Cloud Contract Wiremock » 2.1.1.RELEASE
When I register java Time module in the Json.getObjectMapper().registerModule(New JavaTimeModule()) it does not work.
In this version I checked the of **getObjectMapper()** is of ****Wiremock.com.fasterxml.jackson.databind.ObjectMapper type.**

Can you please tell why there is discrepancy?

**Comment by smathangi** [comment]
I still see this as issue on latest 'wiremock-jre8-standalone', version: '2.26.3'

**Comment by kzander91** [comment]
Still in issue for me on 2.31.0. Using `okForJson(object)` fails if the `object` contains `java.time` types with the error `wiremock.com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type 'java.time.Instant' not supported by default: add Module "wiremock.com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling`.

That module doesn't exist, so I can't register it.

**Comment by tomakehurst** [comment]
I think just adding the time module by default might be simplest here

**Comment by xenoterracide** [comment]
workaround?

**Comment by xenoterracide** [comment]
using `JavaTimeModule` does not work.

```
    wiremock.com.fasterxml.jackson.databind.exc.InvalidDefinitionException at DevExchangeOauth2FeignRequestInterceptorTest.kt:31
```
and the existing error is massively confusing.

**Comment by mark-henry** [comment]
Still a problem on wiremock-jre8-standalone 2.35.0
