### ISSUE TITLE
[Feature Request] Change to new version of Github issue templates (YAML)

### ISSUE THREAD

**Issue by mrk-han** [wiremock/wiremock#1129]
## Feature requests

Please include details of the use case and motivation for a feature when suggesting it.

This is a feature request to switch to the new YAML format for specifying multiple issue templates. This would allow us to have a separate template for Bugs vs Feature Requests.

See: https://help.github.com/en/articles/about-issue-and-pull-request-templates

**Comment by oleg-nenashev** [comment]
Done. `.github` repo is used https://github.com/wiremock/.github/tree/main/.github/ISSUE_TEMPLATE
