### ISSUE TITLE
Dynamic and Global statevariables in API mocking

### ISSUE THREAD

**Issue by DanielCazan** [wiremock/wiremock#1142]
Thank you so much for a great mocking tool - I *love* how easy it is to use!  One thing that is a causing me some problems is going to a specific state with a single req

**Scenario**:
StateHappy: returns 200
StateBad: returns 404
StateException: returns 500
...
[implement n states]

Some states (non-sequential / dependent on each other) check behavior around StateHappy, some around various errors, etc.

**Current ways to have a test hit a specific endpoint:**
- Use a unique ID in the query to determine which scenario catches things.  Downside: Things get tangled when using more than one mock in a sequence (with the same body passed between them), messy to keep track of which IDs do what
- For each scenario have one request that sets newScenarioState to 'go to it'.  Downside: Doubles the number of mocks needed / tracked - for each mock you have to have a second stub to reach it
- Call the same endpoint multiple times, each time 'moving to the next state' until you reach the expected state.  Downside: super messy, have to remember how many times to call things to get to a specific state

**Ideal Outcome** 
```
{
  "scenarioName": "Some Scenario",
  "request": {
    "method": "GET",
    "urlPattern": "/state_change/.*"
  },
  "response": {
    "status": 200,
    "body": "State changed to {{request.path.[1]}",
    "transformers": ["response-template"]
  },
  "newScenarioState": {
     "scenarioName": "Some Scenario"
     "state": "{{request.path.[1]}",
     "transformers": ["response-template"]
   }
}
```

Extending the response-template option to newScenarioState to allow dynamically setting the new state for a given scenario.  Then a user / test can call this endpoint to set states, then that endpoint can be checked normally and will respond based on their state

**Comment by pedroccrl** [comment]
Hello,
There is any update or workaround on this feature? Can't figure out an way of doing a chain of requests/states with the last one knows the response of the first.

I think it's similar with the issue #1027.

**Comment by lfalcantar** [comment]
I was thinking with Dynamically state to allow users to set a specific request body field or part of the url to keep track of the state. 

for example http://api/jobs/4312/status Created
for example http://api/jobs/4312/status Pending
for example http://api/jobs/4312/status Completed

for example http://api/jobs/9876/status Created
for example http://api/jobs/9876/status Pending
for example http://api/jobs/9876/status Completed


then in the mapping we can specify the order of states and also a unique key, then the code will figure out what state to return based on the unique id. This means that multiple request in different order for 9876, 4312 or any unique id can be sent to the server. 

The only worry is how many can you keep in memory but can be limited by a config.

**Comment by ioanngolovko** [comment]
It will be nice imrovement. Especially with ttl when we can clear sleeping scenarios in given time. Alsow is should be cleared after the completing of its life cycle.

End user will take all responsibility of memory restrictions with ttl mechanics.

**Comment by tomakehurst** [comment]
I've been thinking about this on and off, and I agree it would be very useful in some circumstances.

However, I think there are a number of tricky design choices to be made, including:

**How do we express the logic for retrieving/transforming/storing state?**
I've actually spiked this in the past using templates and it was pretty ugly, so I'm not hugely in favour of doing this.
Alternative options might be a hook that runs Javascript to push/pull things from storage, or some kind of restricted expression language.

**How far do we go?**
We could just say there's a simple key/value store and it's up to you to munge things in and out of this.
OTOH we could go further and have primitives for lists, stacks, nested maps etc.
I also tried this in my template-based spike, and felt I'd gone too far with several of the above primitives. So perhaps simple k/v would be best.

**How do we ensure memory and storage aren't exhausted?**

**Comment by ioanngolovko** [comment]
Wiremock is intended for test cases. Below are my suggestions.

**How do we express the logic for retrieving/transforming/storing state?**
I trust you as a maintainer in this question. If templating is ugly and hard to support then some kind of EL will be suitable solution. All we need is to associate the steps with some attribute or multiple attributes. It can be any json object (number, string, etc.)


**Memory/storage**
We don't keep that data for a long. Test infrastructure usually isn't high loaded.
QA engineers almost always do the same things - the checking  of one or another specific process. 

So there is no problem with memory in most cases. 
We can set default ttl for 1 minute for each scenario step if not manually specified.

Of course, in cases of stress testing mem/storage can be overflowed. But this kind of testing needs to be properly prepared, especially by the hardware.

Every application can be broken due to bad maintenance. What happen's if someone will generate different stubs inside infite loop?

**Kind of storage**
Sure, k/v is simple and does not require complex approaches.

**Comment by nvspradeep** [comment]
@lfalcantar for the scenario you provided,

I guess we can achieve via a workaround using transformer and caching

`public class DynamicResponseTransformer extends ResponseTemplateTransformer {
    Cache<String, Integer> responseCache = Caffeine.newBuilder()
            .expireAfterWrite(1, TimeUnit.HOURS)
            .build();

    public DynamicResponseTransformer() {
        super(true);
    }

    @Override
    public ResponseDefinition transform(Request request, ResponseDefinition responseDefinition, FileSource fileSource, Parameters parameters) {
        // Extract the job ID from the request path
        String path = request.getUrl();
        String[] pathSegments = path.split("/");
        String jobId = pathSegments[pathSegments.length - 2];

        // Get the current count for this job ID
        Integer count = responseCache.get(jobId, key -> 0);

        // Update the count for this job ID
        responseCache.put(jobId, count + 1);

        // Build the response based on the job ID and count
        ResponseDefinitionBuilder responseBuilder = ResponseDefinitionBuilder.like(responseDefinition);

        switch (count) {
            case 0:
                // Return "Created" for the first call for each job ID
                responseBuilder.withBody("Created");
                break;
            case 1:
                // Return "applied" for the second call for each job ID
                responseBuilder.withBody("applied");
                break;
            case 2:
                // Return "done" for the third call for each job ID
                responseBuilder.withBody("done");
                break;
            default:
                // Return an error message for any subsequent calls for each job ID
                responseBuilder.withStatus(500)
                        .withBody("Maximum number of calls exceeded for job ID " + jobId);
        }

        return responseBuilder.build();
    }
}`

**Comment by nvspradeep** [comment]
Using transformers & Cache 

```
public class DynamicResponseTransformer extends ResponseTemplateTransformer {
    Cache<String, Integer> responseCache = Caffeine.newBuilder()
            .expireAfterWrite(1, TimeUnit.HOURS)
            .build();

    }

    @Override
    public ResponseDefinition transform(Request request, ResponseDefinition responseDefinition, FileSource fileSource, Parameters parameters) {
        // Extract the job ID from the request path
        String path = request.getUrl();
        String[] pathSegments = path.split("/");
        String jobId = pathSegments[pathSegments.length - 2];

        // Get the current count for this job ID
        Integer count = responseCache.get(jobId, key -> 0);

        // Update the count for this job ID
        responseCache.put(jobId, count + 1);

        // Build the response based on the job ID and count
        ResponseDefinitionBuilder responseBuilder = ResponseDefinitionBuilder.like(responseDefinition);

        switch (count) {
            case 0:
                // Return "Created" for the first call for each job ID
                responseBuilder.withBody("Created");
                break;
            case 1:
                // Return "applied" for the second call for each job ID
                responseBuilder.withBody("applied");
                break;
            case 2:
                // Return "done" for the third call for each job ID
                responseBuilder.withBody("done");
                break;
            default:
                // Return an error message for any subsequent calls for each job ID
                responseBuilder.withStatus(500)
                        .withBody("Maximum number of calls exceeded for job ID " + jobId);
        }

        return responseBuilder.build();
    }
}
```

**Comment by ioanngolovko** [comment]
Hello mates. You can close this issue due to https://github.com/wiremock/wiremock-extension-state is able to simulate complex scenarios with states.

**Comment by oleg-nenashev** [comment]
I am closing it based on the feedback. Given the importance of the feature, I retrospectively added it to the project roadmap, and I will wok with @dirkbolte @ioanngolovko and other contributors to properly document and announce it. Thanks to all contributors!
