### ISSUE TITLE
Certificate broken for wiremock.org

### ISSUE THREAD

**Issue by Fox32** [wiremock/wiremock#1203]
This is not a bug report for wiremock itself, but for the Wiremock website.

If I connect to `https://wiremock.org/` I get a certificate error, as a wildcard certificate for GitHub is returned instead.

Either something is broken, or [the configuration](https://help.github.com/en/articles/managing-a-custom-domain-for-your-github-pages-site) is incomplete.

**Comment by tomakehurst** [comment]
Not so much broken as never implemented.

It's on my to do list, but there's a bit of work and $$$ involved as I'd need to move the domain to a provider that supports `ALIAS` records.

**Comment by Fox32** [comment]
The documentation says that you don't need an ALIAS record for APEX domains and you can use an A record instead. But I have to experience with GitHub pages.

**Comment by tomakehurst** [comment]
Fixed
