### ISSUE TITLE
Support recording request headers in record mode

### ISSUE THREAD

**Issue by christianbalzer** [wiremock/wiremock#122]
The title says it all... :)

**Comment by leojunior9799** [comment]
`Maybe for the beginning just add a switch to record all of them or none (as of now). Personally, I feel removing superfluous headers is much easier and quicker than adding the necessary ones in`
this option seems sensible

@tomakehurst is it possible to record all request headers as an option? 

E.x.`"RecordAllHeaders" : "true", `
