### ISSUE TITLE
FileNotFoundException when stubbing json file to be returned

### ISSUE THREAD

**Issue by ladams81** [wiremock/wiremock#129]
I have the json file in the src/test/resources/__files directory yet when my client application sends a GET request and tries to get a response containing the json from the server this exception gets thrown;

java.lang.RuntimeException: java.io.FileNotFoundException: src/test/resources/__files/product.json (No such file or directory)

My current directory is /Users/lawjoners/IdeaProjects/lekky/src

This is my stub method:

   stubFor(get(urlEqualTo(succesfulGetProductUrl))
        .willReturn(aResponse().withStatus(200)
           .withHeader("Content-Type", "application/json").withBodyFile("product.json")));

Has anybody else had a problem with this or can help me?

**Comment by polaroi8d** [comment]
@ladams81 how you solved the problem?
