### ISSUE TITLE
Enhancement: Require healthcheck that includes version, uptime and response time

### ISSUE THREAD

**Issue by rallygeetha** [wiremock/wiremock#1339]
It would be a nice feature to have a healthcheck endpoint that includes version, uptime and response time. Filing this as per request from Tom Akehurst's reply to my request.

## Bug reports

We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

- [x] Which version of WireMock you're using 

2.26.1

**Comment by ChunjuanLi** [comment]
Hi @tomakehurst ,  I am working on this issue, and I would like to get your suggestion on how to get the version of wiremock. In gradle.build, version is presented, however I can't read the file and get the version value in java code as the config gradle.build won't be compiled. Based on that, I am thinking if we can hard code the version in heathcheck code such as result.setVersion("X.XX.X") or create a java config file to contain the version such that healthcheck can read the data from this java file, the downside of these solutions is that both of the gradle.build and java config/hard coded method are required to be updated together whenever there's a new version of wiremock. Can you please let me know your thoughts on it?

**Comment by tomakehurst** [comment]
A typical solution to this is to write a version info file into the resources folder of the build output so that it's included in the JAR. Then in code you can read this file via the classpath and return the values from it in the response.

Here's an example from one of my projects:

```gradle
task setVersions(type: Copy) {

    def branch = 'git rev-parse --abbrev-ref HEAD'.execute().text.trim()
    def commitHash = 'git rev-parse --verify HEAD'.execute().text.trim()

    from 'src/main/resources/config/versions-template.json'
    into "$buildDir/resources/main/config/"
    rename { fileName ->
        fileName.replace('-template', '')
    }
    expand(
        GIT_BRANCH: branch,
        GIT_HASH: commitHash,
        VERSION: project.version
    )

}
```

And `versions-template.json`:

```json
{
  "version": "${VERSION}",
  "git":{
    "branch" : "${GIT_BRANCH}",
    "hash" :"${GIT_HASH}"
  }
}
```

**Comment by ChunjuanLi** [comment]
@tomakehurst thanks! I will try that and make the code changes.

**Comment by leeturner** [comment]
Hi, not sure if you have seen but we recently merged code from a separate PR to expose the version information. This doesn't include the git branch or hash but could be extended to do so - https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/core/Version.java

**Comment by leeturner** [comment]
We now have a /health endpoint in the admin api that returns the following information:

```json
{
  "status": "healthy",
  "message": "Wiremock is ok",
  "version": "3.8.0",
  "uptimeInSeconds": 30,
  "timestamp": "2024-07-01T21:42:33.965955Z"
}
```

As a result we are now closing this issue
