### ISSUE TITLE
WireMock: stubbing responses from request containing url query parameters

### ISSUE THREAD

**Issue by ladams81** [wiremock/wiremock#134]
Stubbing responses with Wiremock i'm coming up against a peculiar scenario which you might can shed some light on.

Route of request
POSTMAN rest client --> getProducts (with query params) -> MYSERVER --> MOCKSERVER 

When my server receives the GET request from POSTMAN the query params are encapsulated inside a MultiValuedMap which is added to the web resource via the call webResource.queryParams(queryParams);
When i do this my mockserver returns a 404, but returns a 200 otherwise (when this call is not made). I would have though the opposite would have occurred.

my wiremock mapping
![image](https://cloud.githubusercontent.com/assets/7392993/2852243/356a4f88-d131-11e3-9842-a03d40cc909d.png)

The code: (webResource = webResource.queryParams(queryParams) is the critical line.
![image](https://cloud.githubusercontent.com/assets/7392993/2852299/07956312-d132-11e3-96a0-2a96313e8fe3.png)

MockServer logs.
![image](https://cloud.githubusercontent.com/assets/7392993/2852286/da3aa148-d131-11e3-9842-455c09d9af85.png)

I've tried to give as much information as possible. Appreciate any feedback

**Comment by RexCasimir** [comment]
Hi, 
Do you have any steps to soap mocking services using WireMock?. 
Anybody give some idea
Thanks
Rex
