### ISSUE TITLE
[Proxy] Empty Login page(s)

### ISSUE THREAD

**Issue by margasan** [wiremock/wiremock#1389]
# Bug report
Configuration:
- wiremock-jre8:2.27.2
- java 11.0.5 2019-10-15 LTS
- macOS Catalina 10.15.6 (host in which Wiremock server is launched)
- mobile browsers: Safary, Chrome, Android Webview, etc.
- Wiremock configuration:
`wireMockServer = new WireMockServer(wireMockConfig()
                .enableBrowserProxying(true)
                .trustAllProxyTargets(true)
                .port(Integer.parseInt(wireMockHttpPort))
                .bindAddress(wireMockAddress));`

Steps to reproduce:
1. Launch Wiremock as a browser proxy
2. Set proxying on mobile devices (configure ip:port of wiremock proxy, add and trust security certificate
3. Open in browser https://login.live.com/

Actual result:
Empty white page without login, password text fields, and other UI elements appears

Expected result:
Login page with login and password text fields and other UI elements appears

Notes:
1. This happens while open another login/entry point pages, for example, https://mobile.twitter.com
2. This issue is not reproduced with other proxies, like, Charles, Browsermob, etc.

![IMG_0023](https://user-images.githubusercontent.com/18184847/94987092-51af9380-056c-11eb-821d-679ce505ec9b.png)
)

**Comment by margasan** [comment]
It looks like the issue is still not fixed. Reproduced using:
wiremock-jre8 version: '2.32.0'
Could you have a look?

**Comment by tomakehurst** [comment]
Looks like it's related to #1543 this time

**Comment by tomakehurst** [comment]
@margasan OK, looks like it isn't about the CORS headers after all.

When you tested this did you trust the WireMock root certificate you can grab from http://localhost:8080/__admin/recorder ?

**Comment by margasan** [comment]
> When you tested this did you trust the WireMock root certificate you can grab from http://localhost:8080/__admin/recorder ?
Sure, the root CA is installed and trusted on the mobile device, so can to proxy all https traffic.

**Comment by tomakehurst** [comment]
OK, having tested it again I've reverted to my original belief that it's about CORS headers.

Try setting `--enable-stub-cors` or `.stubCorsEnabled(true)` on WireMock's startup.

**Comment by margasan** [comment]
> Try setting `--enable-stub-cors` or `.stubCorsEnabled(true)` on WireMock's startup.
Tried. No luck.

**Comment by tomakehurst** [comment]
@margasan I don't think this is a WireMock bug (any more at least) so I suggest you drop into the mailing list or community Slack if you want a hand getting this working.

**Comment by margasan** [comment]
> @margasan I don't think this is a WireMock bug (any more at least).
In my opinion this is the issue of proxy implementation which is used in WireMock. Other proxies like fiddler/charles/mitmproxy don't have such problem.
