### ISSUE TITLE
Upgrade to HTTP client 5.x

### ISSUE THREAD

**Issue by tomakehurst** [wiremock/wiremock#1481]
Track the latest and greatest now that it's GA.

Also, fix #627

**Comment by timtebeek** [comment]
Started with a first attempt here: https://github.com/wiremock/wiremock/compare/master...timtebeek:http-client-5.x
Not sure if I'll be able to get every last detail working, but it's a start. :)

Figured to first get this working as much as possible, and only once that's done separately and gradually improve handling of closeables for instance.

**Comment by tomakehurst** [comment]
I've been doing a bit of thinking about this recently and I think there's an opportunity to make WireMock more portable while doing this.

A long term goal I have is to split WireMock up a bit, creating a smaller core with abstractions around key integration points such as the proxy HTTP client.

One advantage of this is that users on other platforms e.g. Android and (possibly) some serverless frameworks can choose an implementation that works well for them in terms of compatibility/performance/size etc.

Another is that, since Java 11+ now has a decent HTTP client and server, the core version could work without the need for 3rd party dependencies for either.

So since we already have a `Request` and `Response` pair of interfaces, I'd like to propose also adding our own `HttpClient` interface around these, which is settable in `WireMockConfiguration` and defaults to the HTTPClient 5.x implementation.

What do you think?
