### ISSUE TITLE
Please add support for starting up with a randomly selected (available) port.

### ISSUE THREAD

**Issue by karlmdavis** [wiremock/wiremock#151]
Jetty, the JDK's `ServerSocket` class, and other network-based tools allow specifying `0` as a port. When this is done, the service will randomly select an available port and start up on that port. This is particularly useful for unit tests, as it allows them to be run in parallel. It's even more important when multiple builds might be running on the same box, as it prevents the need for "assigning" testable port numbers to each build, which quickly gets complicated to keep track of.

Looking at the WireMock code, it seems there is no support for this. Even if a port of `0` is passed into Jetty or whatever you're using under the hood, I don't see any way to get the actual port back out.

**Comment by handstandsam** [comment]
```java
@Rule
public WireMockRule wireMockRule = new WireMockRule(wireMockConfig().dynamicPort());
```
