### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space issue.

### ISSUE THREAD

**Issue by pradipkumarmodi** [wiremock/wiremock#152]
I am using wiremock as mock server for performance testing and after hitting request to wiremock continuously for 2hrs, it starts throwing java.lang.OutOfMemoryError: Java heap space exception.

**Comment by alwindoss** [comment]
Could you send me the link to the solution. I am facing a similar issue

**Comment by tomakehurst** [comment]
The request journal filling up is probably the reason this is happening. Suggest either resetting periodically, or disabling the request journal (which you can only do if you don't need to use the find or verify calls).
