### ISSUE TITLE
With --print-all-network-traffic switch enabled, console log is littered with decoding errors for proxied request/response bodies which are not decodable

### ISSUE THREAD

**Issue by jslew** [wiremock/wiremock#1541]
WireMock version: Latest master branch as of 6/22/2021
Starting `com.github.tomakehurst.wiremock.standalone.WireMockServerRunner` with arguments `--port 1080 --verbose --enable-browser-proxying --print-all-network-traffic`

The console has a lot of errors coming from the code below (`ConsoleNotifyingWiremockNetworkTrafficListener`).  It is blindly decoding body bytes, assuming (I think) that they always contain UTF-8 text bytes.  When they do not (an image response, for example, or some other encoding of text), an error is thrown and hits the console with a stack trace (see the two commented out lines).  I don't think this needs to be too smart, but it may make sense to simply log  "[Non-UTF-8 Response]" or something in the catch handler, or a hex representation of the bytes.

```
 @Override
    public void incoming(Socket socket, ByteBuffer bytes) {
        try {
            CONSOLE_NOTIFIER.info("Incoming bytes: " + decoder.decode(bytes));
        } catch (CharacterCodingException e) {
            //CONSOLE_NOTIFIER.error("Problem decoding network traffic", e);
        }
    }

    @Override
    public void outgoing(Socket socket, ByteBuffer bytes) {
        try {
            CONSOLE_NOTIFIER.info("Outgoing bytes: " + decoder.decode(bytes));
        } catch (CharacterCodingException e) {
           // CONSOLE_NOTIFIER.error("Problem decoding network traffic", e);
        }
    }
```

Our use case is: we are using browser-proxying mode and snapshotting to record all requests, and were trying to debug an unrelated issue.  This was making the logs very noisy.

**Comment by blacelle** [comment]
This also happens on gzipped content.

**Comment by bmodi2** [comment]
Was there a way to make this work for gzipped content @blacelle

**Comment by blacelle** [comment]
I can't remember, sorry
