### ISSUE TITLE
https://nexus.awstrp.net/assets/index.html#/vulnerabilities/sonatype-2012-0050

### ISSUE THREAD

**Issue by alexmnyc** [wiremock/wiremock#1567]
https://nexus.awstrp.net/assets/index.html#/vulnerabilities/sonatype-2012-0050

Upgrade to 
```
implementation group: 'commons-codec', name: 'commons-codec', version: '1.15'
```

**Comment by tomakehurst** [comment]
The URL you've shared is not public. Can you share some publicly available context please?
