### ISSUE TITLE
"equalToDateTime" : "now"

### ISSUE THREAD

**Issue by NewbieProger** [wiremock/wiremock#1571]
```
 {
   "request" : {
     "url" : "/dates",
     "method" : "POST",
     "body" : {
       "matchesJsonPathe" : {
         "expression": "$.date",
         "equalToDateTime" : "now",
         "actualFormat" : "dd/MM/yyyy"
       }
     }
  }
 }
```

Please, give an opportunity use it so 
We need a dynamical dates, offset to it, and formatting

**Comment by NewbieProger** [comment]
If i use so

![image](https://user-images.githubusercontent.com/34659664/127374626-81edb83c-1bf3-4230-8d94-9b8a800f25a4.png)
It doesnt match

And if I use just "now"

**Comment by tomakehurst** [comment]
I think you need to truncate the actual to the nearest day, otherwise it'll be unequal due to the hours/mins/seconds of the actual time.

**Comment by NewbieProger** [comment]
` otherwise it'll be unequal due to the hours/mins/seconds of the actual time.`
May be do, that "now" won't use time when comparing?
