### ISSUE TITLE
Proxied Delete requests missing the body

### ISSUE THREAD

**Issue by rlachu** [wiremock/wiremock#1573]
We are proxying requests to another server and we see that for post, put and patch the body goes to the proxied server. But for the delete request, the body is not proxied. We see the following at src/main/java/com/github/tomakehurst/wiremock/http/ProxyResponseRenderer.java#L94

        addBodyIfPostPutOrPatch(httpRequest, responseDefinition);
 
So the body not added if it is delete. Not sure why though? Spec does not explicitly forbade deletes from having body
https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

Can someone shed somelight

**Comment by tomakehurst** [comment]
Please see #627
