### ISSUE TITLE
Upgrade Gradle to 7+ to support JDK 17 test runs

### ISSUE THREAD

**Issue by timtebeek** [wiremock/wiremock#1633]
After https://github.com/wiremock/wiremock/pull/1632 it might be good to also start running the tests on JDK 17.
For this to work we have to upgrade Gradle to the latest version, 7.2 [or even 7.3 when released](https://github.com/gradle/gradle/issues/16857).

As we're coming from Gradle 6.6.1, there's [quite a few upgrade steps involved](https://docs.gradle.org/7.2/userguide/upgrading_version_6.html).
Most notably [the removal of the `compile` and `runtime` configurations](https://docs.gradle.org/7.2/userguide/upgrading_version_6.html#sec:configuration_removal),
as well as [removal of the legacy `maven` plugin](https://docs.gradle.org/7.2/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin).

@nstdio already opened a pull request to remove baseName for archive tasks: https://github.com/wiremock/wiremock/pull/1621

**Comment by tomakehurst** [comment]
Closed by 72cfe156a96665535dd1c3555e3990e7413a1595
