### ISSUE TITLE
Expose remove stub mapping by ID through admin client (HttpAdminClient)

### ISSUE THREAD

**Issue by marekpietrasz** [wiremock/wiremock#1684]
Would be great to allow to delete a stub mapping by ID using admin client.

Current behaviour of method `wireMock.removeStubMapping` on external server leads to post request with json body that in our case matches too many mappings (we have a problem with multiple mappings to the same url and body but this is separate issue). 

After checking existing implementation method `removeStubMapping` on `HttpAdminClient` is using `OldRemoveStubMappingTask`. There is also `RemoveStubMappingTask` that probably was designed to be used against `/__admin/mappings/{id}` but is not exposed AFAIK

Would be great to expose existing `RemoveStubMappingTask` and allow to remove mappings by ID to allow better management of stubs (in ideal world stubs are well defined and existing method is good enough but this is not the case for us)

**Comment by tomakehurst** [comment]
Yeah, I agree this should be exposed in the Java client, since it's available via REST.

**Comment by Patrolfr** [comment]
I'm working on it.

**Comment by Patrolfr** [comment]
PR: https://github.com/wiremock/wiremock/pull/1986
