### ISSUE TITLE
%3d is url decoded incorrectly

### ISSUE THREAD

**Issue by Smitty010** [wiremock/wiremock#1700]
I am using wiremock 2.31.0 along with webhook.  I have a form parameter with a value of "http://localhost:8080/fred/bill?id=eyJhbGci".  (so, in the form, it looks like "callback_url=http://localhost:8080/fred/bill?id=eyJhbGci" -- before the url encoding). 
 When url encoded, it looks like: "callback_url=http%3A%2F%2Flocalhost%3A8080%2Ffred%2Fbill%3Fid%3DeyJhbGci".  So far, so good.  That's what I see in the logs for the http calls.

In the webhook code, I access the value with the following expression: "{{formData originalRequest.body 'form' urlDecode=true}}{{form.callback_url}}".  The value is used as the webhook url ("withUrl()") value for the callback.  However, the URL I get is:  "http://localhost:8080/fred/bill?id&#x3d;eyJhbGci".  Note what happened to the equal sign for the parameter "id".  I understand that "&#x3d;" is an equal sign for an html entity.  But it doesn't work in a url.  

I tried several online url encode/decode.  None of them decodes the equal sign to the html entity.

This seems like a bug.  Am I missing something?

**Comment by tomakehurst** [comment]
You need to use triple braces, which is the "don't escape" syntax, so e.g. `{{{form.callback_url}}}`

**Comment by Smitty010** [comment]
That fixed the problem.

I'll look for the triple brace documentation.

Thanks

Scott
