### ISSUE TITLE
The response templating is not work when spec the tranformer name in json with default setting

### ISSUE THREAD

**Issue by wangpeng2020** [wiremock/wiremock#1713]
# Response Templating is not work.
   the response templating is not work when spec the tranformer name in json with default setting

# Env
- [ ] Which version of WireMock you're using
     ```standalone 2.31.0```

- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line
      ```java -jar wiremock-jre8-standalone-2.31.0.jar --port 8080```

# Steps
- the mapping is
```
{
"request": {
    "method": "POST",
    "url": "/sceen/channel/v1.0/create"
  },
  "response": {
    "body": "{\"TaskID\": \"{{jsonPath request.body '$.TaskID'}}\",\"StatusCode\":\"0\",\"Description\":\"ok\"}",
    "headers": {
      "Content-Type": "application/json"
    },
    "transformers": [
      "response-template"
    ],
    "status": 200
  }
}
```
- the request is:
```curl --request POST 'http://localhost:8080/sceen/channel/v1.0/create' --header 'Content-Type: application/json' --data '{"TaskID":"12345"}'```
- and the response:
```
{
    "TaskID": "{{jsonPath request.body '$.TaskID'}}",
    "StatusCode": "0",
    "Description": "ok"
}
```

# Investigate
   if i  run the jar with below cmdline, the issue will gone.
   ```java -jar wiremock-jre8-standalone-2.31.0.jar --port 8080 --global-response-templating```

**Comment by tomakehurst** [comment]
This still requires the transformer to be loaded, so you need to pass `--local-response-templating` to the CLI.

```
"transformers": [
      "response-template"
    ]
```

**Comment by wangpeng2020** [comment]
> 



> This still requires the transformer to be loaded, so you need to pass `--local-response-templating` to the CLI.
> 
> ```
> "transformers": [
>       "response-template"
>     ]
> ```

get it，thanks for your explain！
