### ISSUE TITLE
Wiremock Doesn't Mock the Webclient Request

### ISSUE THREAD

**Issue by mgnfcnt** [wiremock/wiremock#1716]
I am using spring boot 2.5.7, java 8 and junit 5.(I also used wiremock-jre but issue is same)

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.7</version>
		<relativePath />
	</parent>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-contract-wiremock</artifactId>
			<version>3.0.4</version>
			<scope>test</scope>
		</dependency>

My integration test class:

    @SpringBootTest(classes = MyTestApplication.class, webEnvironment = WebEnvironment.RANDOM_PORT)
    @AutoConfigureWireMock(port = 0)
    @DirtiesContext
    public class MyTestControllerTest {
    
      @LocalServerPort
      private int port;
    
      @Autowired
      private TestRestTemplate restTemplate;
    
      @BeforeEach
      void init() {
        stubFor(post(urlPathEqualTo("http://localhost:8443/my-third-party-endpoint"))
            .willReturn(aResponse()
                .withStatus(200)
                .withHeader("Content-Type", MediaType.APPLICATION_JSON.toString())
                .withHeader("Accept", MediaType.APPLICATION_JSON.toString())
                .withBody("{}")));
      }
    
      @Test
      public void testAddEmployee() {
        PartInspectionImageModel partInspectionImageModel = new PartInspectionImageModelProvider().createPartInspectionImageModel();
    
        ResponseEntity<PartInspectionImageModel> responseEntity = this.restTemplate
            .postForEntity("http://localhost:" + port + "/rest/my-test-endpoint", partInspectionImageModel, PartInspectionImageModel.class);
    
        assertEquals(200, responseEntity.getStatusCodeValue());
      }
    }

Code piece to be mocked by wiremock inside my implementation class:

     WebClient webClient = WebClient.create("http://localhost:8443");

      Mono<String> postPartInspectionImageModelToML = webClient.post()
          .uri("/my-third-party-endpoint")
          .contentType(MediaType.APPLICATION_JSON)
          .accept(MediaType.APPLICATION_JSON)
          .body(Mono.just(completeMlProcessingModel), CompleteMlProcessingModel.class)
          .retrieve()
          .bodyToMono(String.class);

      String response = postPartInspectionImageModelToML.block();

Due to it can't be mocked, test failing at postPartInspectionImageModelToML.block() phase.

Error is only:

> Caused by: java.net.ConnectException: Connection refused: no further
> information

**Comment by jamietanna** [comment]
Hey @mgnfcnt where3 did you specify the port for Wiremock to start on `8443`? By default it's on `8080`, so it's worth amending your code to:

```diff
- WebClient webClient = WebClient.create("http://localhost:8443");
+ WebClient webClient = WebClient.create("http://localhost:8080");
```

Additionally, this doesn't look quite right to me - I think you can do it as just:

```diff
-    stubFor(post(urlPathEqualTo("http://localhost:8443/my-third-party-endpoint"))
+   stubFor(post(urlPathEqualTo("/my-third-party-endpoint"))
```

**Comment by mgnfcnt** [comment]
@jamietanna "http://localhost:8443" this is another service i need to call that is why i am creating webclient with this base-url. I cant change it to 8080 because that service running on 8443 port

**Comment by jamietanna** [comment]
For this example though, we're trying to test through Wiremock though, right?

**Comment by mgnfcnt** [comment]
I am trying to create integration test for specific endpoint. In my implementation class i have webclient call. I am trying to mock this request with wiremock. thats all

**Comment by jamietanna** [comment]
So the first thing we need to do is to inject in `"http://localhost:8443"` (via the constructor or `@Value` for a field) so we can stub it out for the purpose of this test, because:

- it's a better practice so you can change it more easily in the future
- it allows us to have one value for the tests, and one for Production code

**Comment by tomakehurst** [comment]
I suggest taking this to the mailing list or Stackoverflow, since it's a Spring integration question rather than bug or enhancement request.
