### ISSUE TITLE
Since 2.28.0 wiremock is much more slower on macOS Big Sur

### ISSUE THREAD

**Issue by marcindabrowski** [wiremock/wiremock#1718]
When upgrading from 2.27.2 to any newer version my tests are 4 times slower.
I'm running tests on macOS Big Sur with Java version 11 or newer.
I was using AdoptOpenJDK and Temurin.
Tests are run using Gradle 7.1.

The same situation is with GitHub Action with Temurin 11.

**Comment by tomakehurst** [comment]
Please could you post profiler output from your test runs before and after the upgrade?

**Comment by marcindabrowski** [comment]
I noticed that you released 2.32.0, and checked with it, and now it is working fast.
Thanks.

**Comment by tomakehurst** [comment]
Thanks for the update.

This is a surprising result as I didn't think we'd done anything in this release likely to affect performance very much.

**Comment by marcindabrowski** [comment]
Should I close the issue?

**Comment by marcindabrowski** [comment]
I'm not sure if it was connected to Wiremock, because on my team members who were using macOS Catalina it was working fast.

**Comment by tomakehurst** [comment]
Let's close it. It sounds like all's well in the current version, so nothing to investigate.
