### ISSUE TITLE
New release with log4j updated

### ISSUE THREAD

**Issue by mickybar** [wiremock/wiremock#1737]
When will you release a new version with the log4j vulnerability addressed?

**Comment by tomakehurst** [comment]
WireMock doesn't use log4j other than in its test suite so a new release won't change anything.

Do you have tools that are flagging this despite log4j not appearing in the POM?

**Comment by mickybar** [comment]
No, not really, I just use the tool "off the shelf" so, as long as it does not have any impact I'm ok with it
