### ISSUE TITLE
StubMappingTransformer not called when --record-mappings is specified when running in standalone mode

### ISSUE THREAD

**Issue by petermant** [wiremock/wiremock#1748]
Hi,

I am registering a StubMappingTransformer when running wiremock 2.32.0 as a standalone process via the extensions command line option.

I can run the standalone JAR - which I've built as a far jar including my extension classes - in debug mode in IntelliJ and see that the extension is successfully being registered because the getName method is called during ExtensionLoader::loadExtension.

My extension is currently very simple:

```
public class AccreditationStubMappingTransformer extends StubMappingTransformer {
    private Logger logger = LoggerFactory.getLogger(this.getClass());

    @Override
    public StubMapping transform(StubMapping stubMapping, FileSource files, Parameters parameters) {
        logger.info("Stub mapping id {}, request {}, and response {}", stubMapping.getId(), stubMapping.getRequest().getUrlPath(), stubMapping.getResponse().getBody());
        return stubMapping;
    }

    @Override
    public String getName() {
        return "AccreditationStubMappingTransformer";
    }
}

```

Unfortunately, it is never called when I make requests via wiremock.  The command line I am running is as follows, minus all the junk IntelliJ adds for debugging purposes:

```
java  -jar accreditation-wiremock-1.0.61-SNAPSHOT-all.jar --record-mappings --root-dir=./accreditation-wiremock/wiremock-config/inbound --proxy-all=http://localhost:8254 --extensions=com.mypackage.wiremock.AccreditationStubMappingTransformer --port=8256 --verbose
```

The javadoc for `StubMappingTransformer` says that it "allows transforming stub mappings recorded via the snapshot and recording API endpoints."

In `Recorder::getStubMappingPostProcessor` I can find a reference to the StubMappingTransformer class in a call to `options.extensionsOfType(StubMappingTransformer.class)`. `This is used in Recorder::takeSnapshot`.

Given that I'm running this as a standalone JAR with the `record-mappings` option, instead it uses `StubMappingJsonRecorder` - which does not call the StubMappingTransformers in the manner described above.

I'm going to submit this as a bug, as it appears the JavaDoc suggests the StubMappingTransformer should be called - and you'd expect that extension behaviour to be consistent regardless of whether the recording is started via the API or via the command line. 

In the meantime I'll check out the source and try to fix it by amending the StubMappingJsonRecorder in a similar manner to the usage from the Recorder class.

**Comment by tomakehurst** [comment]
`--record-mappings` is the legacy record mode, is deprecated and will be removed in 3.x. If you want to use transformers you'll need to use the new recorder.

**Comment by petermant** [comment]
Oh, interesting.  I'm not clear then - what's the non-legacy way of starting recording from the command line / standalone? 
Or is the whole of standalone mode going to disappear also?

**Comment by tomakehurst** [comment]
Via the recorder UI page or an API call:
http://wiremock.org/docs/record-playback/

Standalone is here to stay.
