### ISSUE TITLE
Human readable id

### ISSUE THREAD

**Issue by luisfranciscob** [wiremock/wiremock#1750]
Use any string as id instead of an UUID. It is easier to understand what we are doing when we are editing a stub called "purchase_order_response"  instead of 123e4567-e89b-12d3-a456-426614174000.

**Comment by tomakehurst** [comment]
There's a `name` field available on stub mappings for this purpose.

Switching away from UUIDs as the actual ID would present potential issues with non-uniqueness and be a breaking change to the Java API, so this isn't something we'll do.

**Comment by luisfranciscob** [comment]
But how can I edit a mock using its name?
