### ISSUE TITLE
Wiremock not including Content-length header

### ISSUE THREAD

**Issue by luisfranciscob** [wiremock/wiremock#1755]
I have to manually add the Content-length header, which is hard to maintain because I have to recalculate it by myself every time I change the content of the file in bodyFileName.

I know that probably there is some better way to do it rather than manually.

Thanks in advance.

**Comment by tomakehurst** [comment]
See http://wiremock.org/docs/configuration/#transfer-encoding

For future reference - if you've got questions, rather than bug reports or enhancement requests, please post them to the mailing list.
