### ISSUE TITLE
404Not Found When deploy application on Azure Cloud 

### ISSUE THREAD

**Issue by javahonk** [wiremock/wiremock#1839]
# Issue guidelines

If you're asking a question, rather than reporting a bug or requesting a feature, **please post your question on the [mailing list](https://groups.google.com/forum/#!forum/wiremock-user), and do not open an issue**.

Please do not log bugs regarding classpath issues (typically manifesting as 'NoClassDefFoundException' or 'ClassNotFoundException').
These are not WireMock bugs, and need to be diagnosed for your project using your build tool. Plenty has already been written in WireMock's issues and mailing list about how to resolve these issues
so please search these sources before asking for help.

## Bug reports

We're a lot more likely to look at and fix bugs that are clearly described and reproduceable. Please including the following details when reporting a bug:

- [ ] Which version of WireMock you're using --> 2.27.2
- [ ] How you're starting and configuring WireMock, including configuration or CLI the command line - This is an Spring boot application and executable jar deployed on Azure cloud
- [ ] A failing test case that demonstrates the problem- Below is the class: 
@RestController
@RequiredArgsConstructor(onConstructor = @__(@Autowired))
@Slf4j
public class WiremockController {

	private final WireMockApp wireMockApp;

	@SuppressWarnings({ "rawtypes", "unchecked" })
	@RequestMapping(path = "/**")
	public ResponseEntity<String> getResponse(HttpServletRequest httpServletRequest) {
		ServeEvent serveEvent = wireMockApp.serveStubFor(new WireMockHttpServletRequestAdapter(httpServletRequest, new DefaultMultipartRequestConfigurer(), StringUtils.EMPTY));
		ResponseDefinition responseDefinition = serveEvent.getResponseDefinition();
		
		return new ResponseEntity(responseDefinition.getBody(), transformHttpHeaders(responseDefinition.getHeaders()), HttpStatus.resolve(responseDefinition.getStatus()));
	}

	private HttpHeaders transformHttpHeaders(com.github.tomakehurst.wiremock.http.HttpHeaders wiremockHttpHeaders) {
		HttpHeaders headers = new HttpHeaders();

		if (wiremockHttpHeaders != null) {
			wiremockHttpHeaders.all().stream().forEach(httpHeader -> headers.addAll(httpHeader.key(), httpHeader.values()));
		}

		return headers;
	}

	
}

- [ ] Profiler data if the issue is performance related   - Not applicable 
- [ ] My configuration: application.yaml:
azure:
  keyvault:
    enabled: false
wiremock:
  stubsMappingFolder: __admin/
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

- [ ] Mappings file located under: \resources\__admin\mappings
- [ ] Note: Locally it works without any issue but when deploy same on Azure cloud its does not work and throw 404 not found

## Feature requests

Please include details of the use case and motivation for a feature when suggesting it.

**Comment by tomakehurst** [comment]
This seems like a request for help deploying to a specific platform rather than a bug report, so please re-post on the mailing list.
