### ISSUE TITLE
Expose WireMock server port as system property

### ISSUE THREAD

**Issue by rbraeunlich** [wiremock/wiremock#1841]
While it works generally quite well to use the @WireMockTest annotation and pass the (random) port from the WireMockRuntimeInfo to the class under test, this approach only works when I can pass in directly the port/url into the class. 

When using e.g. a SpringBootTest with Dependency Injection it's sometimes not possible. Especially, when the server host is read from an application.yaml
Nevertheless, what would work, is when the WireMockExtension would expose random ports as a well known property. Something like 
```
System.setProperty("wiremock.server.port", wireMockServer.port().toString())
```
in a `beforeAll` method would make it possible to reference the port in an application.yaml.

**Comment by straurob** [comment]
Not sure if I understand your question correctly, but would it help to use Spring Boot's `@DynamicPropertySource` in this case?

```java
@RegisterExtension
static WireMockExtension wireMockExtension = WireMockExtension.newInstance()
        .options(wireMockConfig().dynamicPort())
        .build();

@DynamicPropertySource
static void dynamicProperties(DynamicPropertyRegistry registry) {
    registry.add("remote.url", wireMockExtension::baseUrl);
}
```

**Comment by dcalap** [comment]
What about this for Micronaut?

**Comment by dcalap** [comment]
What about this for Micronaut?
