### ISSUE TITLE
Connection refused on stubFor invocation

### ISSUE THREAD

**Issue by UndefinedBehaviour** [wiremock/wiremock#185]
Hello,
I get a java.net.ConnectException: Connection refused on invoation of         stubFor(get(urlEqualTo("localhost"))
                .willReturn(aResponse()
                        .withHeader("Content-Type", "text/plain")));
from within a test method.

In the test class I have the field
    @Rule
    public WireMockRule wireMockRule = new WireMockRule(8080);
and I thought this would be enough.

I am using JUnit 4.11, java 1.7

Am I missing some sort of configuration?

Thank you

Agostino

**Comment by masterchief4049005** [comment]
How can I signup for the mailing list?
