### ISSUE TITLE
Scenario name not serialised to JSON in 2.33.0

### ISSUE THREAD

**Issue by rowanhill** [wiremock/wiremock#1854]
Hi there,

I'm looking at updating wiremock-php to support wiremock 2.33.0. It looks like the 2.33.0 release has removed the `name` field from JSON serialized Scenario objects returned by the admin API. I'm not quite clear if this is intentional or not?

It looks like the change is due to [adding `@JsonIgnoreProperties({"name"})` to Scenario](https://github.com/wiremock/wiremock/blob/70a31fa82c9d34be7b1c3e5cc44e652dc836dba9/src/main/java/com/github/tomakehurst/wiremock/stubbing/Scenario.java#L32) (so it looks intentional), but the same commit includes [a comment referencing keeping JSON backwards compatibility](https://github.com/wiremock/wiremock/blob/70a31fa82c9d34be7b1c3e5cc44e652dc836dba9/src/main/java/com/github/tomakehurst/wiremock/stubbing/Scenario.java#L60) and [the admin API reference still shows a `name` field](https://wiremock.org/docs/api/#tag/Scenarios/paths/~1__admin~1scenarios/get) in the sample response.

Could you please confirm if it's a bug in the API (in which case I'll assume it'll be fixed soon, and not support this in wiremock-php) or if the reference is wrong (in which case I'll look to make wiremock-php consider this an optional field, defaulted to `id` when it's missing, and perhaps mark it as deprecated)?

Thanks,
Rowan

**Comment by tomakehurst** [comment]
Hi Rowan, thanks for flagging this.

You're correct that I intended to leave `name` in there for backwards compatibility but was guilty of not writing a test for this. Patch release on its way...

**Comment by tomakehurst** [comment]
2.33.1 is up now, with this fix
