### ISSUE TITLE
Version mismatched in the API

### ISSUE THREAD

**Issue by fabricereix** [wiremock/wiremock#1860]
Hello,
it seems that is a version mismatch returned by the API.
For the version `2.33.1` , the API `/__admin/docs/swagger` returns `2.32.0`.

This is probably the file to be fixed.
https://github.com/wiremock/wiremock/blob/2.33.1/src/main/resources/swagger/wiremock-admin-api.json

Thanks

**Comment by lepapareil** [comment]
I think there is also a problem with https://github.com/wiremock/wiremock/blob/2.33.1/ui/package.json

```
{
  "name": "wiremock-ui-resources",
  "version": "2.32.0",
```
