### ISSUE TITLE
NEW FEATURE: Does not contain pattern

### ISSUE THREAD

**Issue by ulxanxv** [wiremock/wiremock#1881]
Hello! We had a need for the "does not contain" pattern while using your tool.

**Usage example :**
We have multiple query parameters "groups" in a URL: http://localhost:1111/test-stub?groups=Qwerty&qroups=Qwerty2

So we need to do something like

```
...
"id" : "c459a482-5b18-4c12-a17f-be2834fd6cdf",
"name" : "mapping-name",
 "request" : {
      "urlPath" : "/test-stub",
      "method" : "GET",
      "queryParameters" : {
           "groups" : {
                "doesNotContains" : "Qwerty"
         }
...
```

With this configuration, the stub should not be found.
Can you add this to WireMock?

**Comment by ulxanxv** [comment]
Yes, it could be used, but such an entry gives an incorrect result.
Only the first parameter is checked.

**Example**
http://localhost:1111/test-stub?groups=Qwert2&groups=Qwerty

In such a request, a stub will be found

**Comment by KirillNNRUS** [comment]
Hello. When are You planned add this feature to release?

**Comment by pks-1981** [comment]
@tomakehurst @oleg-nenashev 
Hello
Did I understand correctly that everything is done?
Maybe close that?

**Comment by shivangi-pandey** [comment]
does this issue still open?

**Comment by tomakehurst** [comment]
Nope, added in 7818ed00ebf5cbebbd505480c57a2db78f9afb60

**Comment by hickford** [comment]
"doesNotContain" missing documentation at https://docs.wiremock.io/request-matching/matcher-types
