### ISSUE TITLE
ResponseTemplateTransformer: proxyUrlPrefixToRemove not filled in when executing the transform method

### ISSUE THREAD

**Issue by ulxanxv** [wiremock/wiremock#1900]
Hello, I recently decided to try using your `Response Templating` (https://wiremock.org/docs/response-templating /) and in general everything works. But the `proxyUrlPrefixToRemove` field was put in my stub, and when the transformation is performed by the class specified in the header, this field is simply not put down, although the code shows that `ProxyResponseDefinitionBuilder` is used there.

_So, example..._
_In the example, I will not use the `Response Templating` functionality, since it works completely. The only problem is filling in the `proxyUrlPrefixToRemove` field_

**FIRST STUB (must make a proxy request for the second stub)**:
```
{
  "id" : "74c2051a-4ecd-48c9-8aed-9f68e9b8eeda",
  "name" : "name",
  "request" : {
    "url" : "/test",
    "method" : "GET"
  },
  "response" : {
    "status" : 200,
    "body" : "{\n    \"response\": \"not a proxy response\"\n}",
    "headers" : {
      "Content-Type" : "application/json"
    },
    "proxyBaseUrl" : "http://localhost:1398/test-2",
    "proxyUrlPrefixToRemove" : "/test",
    "transformers": [
      "response-template"
    ]
  },
  "uuid" : "74c2051a-4ecd-48c9-8aed-9f68e9b8eeda",
  "persistent" : true,
  "priority" : 100,
  "scenarioName" : "group",
  "requiredScenarioState" : "Started",
  "metadata" : {
    "proxyBaseUrl" : "http://localhost:1398/test-2",
    "proxyUrlPrefixToRemove" : "/test",
    "proxyEnable" : true
  },
  "insertionIndex" : 0,
  ...
}
```
**SECOND STUB (the request from the first stub should be redirected to here)**
```
{
  "id" : "af75edb1-dbfc-408a-a1e1-987d6ff34f76",
  "name" : "name-2",
  "request" : {
    "url" : "/test-2",
    "method" : "GET"
  },
  "response" : {
    "status" : 200,
    "body" : "{\n    \"response\": \"proxy response\"\n}",
    "headers" : {
      "Content-Type" : "application/json"
    }
  },
  "uuid" : "af75edb1-dbfc-408a-a1e1-987d6ff34f76",
  "persistent" : true,
  "priority" : 111,
  "scenarioName" : "group-2",
  "requiredScenarioState" : "Started",
  "metadata" : {
    "proxyBaseUrl" : "http://",
    "proxyUrlPrefixToRemove" : "",
    "proxyEnable" : false
  },
  "insertionIndex" : 1,
  ...
}
```

So, as you can see, in the first stub, I filled in the `transformers` field and told him to use a transformer named `response-template` (this is the name I gave to the transformer with the `ResponseTemplateTransformer.class`). Now when calling the first stub, I will go through the `com.github.tomakehurst.wiremock.extension.responsetemplating/ResponseTemplateTransformer.java:90` method.

**BUG**: When calling the first stub, WireMock sends a request to http://localhost:1398/test-2/test although I indicated in the first stub that you need to cut off the prefix /test. The request should be sent to http://localhost:1398/test-2.

_The analysis showed that in this case the transformers forgot to provide for filling in this field or did it intentionally. Don't know. In any case, I believe that this is incorrect functionality._

**Comment by tomakehurst** [comment]
Fixed by 9aad8789d2c470eb9e92df83494a2dcffe90ad06
