### ISSUE TITLE
missing/incorrect equals Method in MultipartValuePattern

### ISSUE THREAD

**Issue by jnt0r** [wiremock/wiremock#1908]
When using multipartPatterns in StubMappings the equals method always fails. When not using multipartPatterns the equals method works correctly. I noticed that the class MultipartValuePattern does not implement an equals Method and wrote a wrapper class that implements the equals method. The equals method on the StubMappings now works as expected.

Is this missing equals method intentional or is it a bug?

This is the wrapper class I use:

```
public class FixedMultipartValuePattern extends MultipartValuePattern
{
    public FixedMultipartValuePattern(String name, MatchingType type, Map<String, MultiValuePattern> headers,
        List<ContentPattern<?>> body)
    {
        super(name, type, headers, body);
    }

    public FixedMultipartValuePattern(MultipartValuePattern mvp)
    {
        super(mvp.getName(), mvp.getMatchingType(), mvp.getHeaders(), mvp.getBodyPatterns());
    }

    @Override
    public boolean equals(Object o)
    {
        if (o == null) return false;
        if (this == o) return true;

        if (Objects.equals(this.getClass(), o.getClass()))
        {
            FixedMultipartValuePattern that = (FixedMultipartValuePattern) o;

            return Objects.equals(this.getName(), that.getName()) 
                    && Objects.equals(this.getBodyPatterns(),that.getBodyPatterns()) 
                    && Objects.equals(this.getHeaders(),that.getHeaders()) 
                    && Objects.equals(this.getMatchingType(), that.getMatchingType());
        }

        return false;
    }
}
```

**Comment by tomakehurst** [comment]
This class doesn't currently have an equals method as within WireMock it's never used in a way that requires it.

In what context do you find the lack of an equals method causes problems?

**Comment by jnt0r** [comment]
I have a use case where I check whether two StubMappings have the same RequestPattern, so I can remove duplicate StubMappings. That's where I use the equals Method.

I think it's very convenient if every class implements the equals method even if it is not required by the main logic.
Would you consider adding the equals method, or should I stick to my wrapper class?

**Comment by tomakehurst** [comment]
OK, I think it makes sense to support that use case, so I'll tag this as an enhancement.

Happy to receive a PR if you feel like creating one.

**Comment by jnt0r** [comment]
I created a PR yesterday. Let me know if you want something to be changed.

**Comment by jnt0r** [comment]
I created another issue/pr with more missing equals/hashcode (#2034). This can be closed.
