### ISSUE TITLE
Support disabling of browser proxy pass-through

### ISSUE THREAD

**Issue by tomakehurst** [wiremock/wiremock#1909]
Currently when browser (forward) proxying is enabled, unmatched requests will be passed through to the target indicated by the originating request.

When purely using this mode for stub serving i.e. playback this isn't always desirable. Although it's possible to set a default stub in order to prevent this, we then lose the diff report when a request isn't matched.

We should therefore add a toggle to enable/disable the passthrough. This should probably be possible (or overridable at least) via the global settings feature so that a record/playback workflow can be completed without needing to restart the instance.

**Comment by kapishmalik** [comment]
@tomakehurst can I take this up?

**Comment by tomakehurst** [comment]
@kapishmalik yes, please do!

**Comment by kapishmalik** [comment]
@tomakehurst cool, thanks. You can assign this issue to me.

**Comment by tomakehurst** [comment]
One design comment - it would be useful for this to be switchable at runtime without restarting. If we allow it to be controlled/overridden by a flag in the global settings object, then it could be toggled on/off via an API call.

**Comment by kapishmalik** [comment]
@tomakehurst just want to check one thing that if passthrough is disabled then what response it should return (404 response  or dummy response)?

**Comment by kapishmalik** [comment]
I took the assumption and raised the PR for the same.

**Comment by tomakehurst** [comment]
> @tomakehurst just want to check one thing that if passthrough is disabled with browser caching then what response it should return (404 response or dummy response)?

I'm not sure browser caching should have any bearing on the behaviour of the pass-through. Can you explain the situation you have in mind in a bit more detail?

**Comment by kapishmalik** [comment]
@tomakehurst we can close this issue. It is done with documentation.

**Comment by tomakehurst** [comment]
Closed in 6bb45ebdc786937896281a711e8bac377235bf03
