### ISSUE TITLE
There is no option to `getScenarios` for non-default client

### ISSUE THREAD

**Issue by nickaden** [wiremock/wiremock#1912]
# Issue guidelines

I'm trying to get Scenarios from my Wiremock server using Wiremock client, but realized that there is only one method - `getAllScenarios()` - which is exposed. I think it's needed to make private method `getScenarios()` as part of client contract.

BTW, I wanted to create pull request to fix it, but was push backed with 403. Is there restriction to create new branches on remote?

## Feature requests

Add method to getScenarios for non-default client

**Comment by tomakehurst** [comment]
That's strange, I've no idea why that's not public, but it definitely should be. I'll fix that in the next release.

**Comment by tomakehurst** [comment]
Fixed in 9792aee49d1f89d32722b7fbf639aeb3a4bdcec6
