### ISSUE TITLE
Support sub-events associated with a ServeEvent

### ISSUE THREAD

**Issue by tomakehurst** [wiremock/wiremock#1913]
Allow child events to be attached to ServeEvent so that useful diagnostic info can be reported/logged e.g. validation results, diff report, parsing errors.

**Comment by kapishmalik** [comment]
@tomakehurst can I pick this up?

**Comment by tomakehurst** [comment]
@kapishmalik I'm planning to work on this myself as there's some detail to it that's not fully articulated here (including some I need to work out).

There's another feature it would be great for you to work on though. If you head over to the [community Slack](https://join.slack.com/t/wiremock-community/shared_invite/zt-1mkbo0zlx-gxeZdTJ15Kchdt888Fn_1A) and DM me, perhaps we can discuss it there?

**Comment by oleg-nenashev** [comment]
It was shipped in 3.0.0
