### ISSUE TITLE
Access standalone wiremock on a different root url

### ISSUE THREAD

**Issue by tarteens** [wiremock/wiremock#1920]
Hi,

I'm trying to the standalone version behind a reverse proxy. 
I want to access the GUI behind http://ip:port/wiremock/__admin/webapp/ (instead of default http://ip:port/__admin/webapp)

I can't find the proper documentation to allow me to change the root servlet context.
It this something that it possible ?

Thanks for the help

**Comment by tomakehurst** [comment]
Please post questions to the mailing list per the issue template instructions
