### ISSUE TITLE
generate randow value alphanumeric string of length to be picked up from request.body parameter supported?

### ISSUE THREAD

**Issue by nilimamoh** [wiremock/wiremock#1934]
My requirement is to make length accept the parameter supplied from request body for the json path & generate a random alphanumeric string of the given length 
but below is not working when i am trying to set the response payload - getting exception : is there a synax issue in below ?  Please suggest correct way to do

{{{randomValue (length jsonPath request.body '$.otpParams.length') type='ALPHANUMERIC'}}}

e.g.
{{randomValue length=33 type='ALPHANUMERIC'}}

instead of hardcoded value for length i need to pass value fetch from request.body (based on input) so need correct syntax for it if supported

**Comment by nilimamoh** [comment]
<title>Error 500 wiremock.com.google.common.util.concurrent.UncheckedExecutionException: wiremock.com.github.jknack.handlebars.HandlebarsException: inline@6e008506:1💯 could not find helper: 'length' {{randomValue type='UUID'}}","callerTransactionId":"caller325782532086010","token":"{{{randomValue (length jsonPath request.body '$.otpParams.length') type='ALPHANUMERIC'}}} ^ </title>

**Comment by tomakehurst** [comment]
This is what you need:

```
{{{randomValue length=(jsonPath request.body '$.otpParams.length()') type='ALPHANUMERIC'}}}
```

Since this is a question, not a bug/feature request please post followup to the mailing list.

**Comment by nilimamoh** [comment]
Thanks for the information.
In the example  below ->length=(jsonPath request.body '$.otpParams.length') - this piece of code will return string for me (length="10"). is there any helper which will convert string to integer.
e.g.
{{{randomValue length=(jsonPath request.body '$.otpParams.length') type='ALPHANUMERIC'}}}
