### ISSUE TITLE
Exception while using the value of a request key having a dot in the name in the response

### ISSUE THREAD

**Issue by DonaldDeep** [wiremock/wiremock#1940]
Wiremock:
=======

Standalone -2.28.1
wiremock-jre - 2.33.2

Descritpion:
=======

Request:
---------

{
  "details":{
  "full.name":"John Doe", 
  "age":30, 
  "city":"Boston"
  }
}

Stub:
-----
trying to get full.name value in the response:

{
  "request":{
    "urlPath":"/path",
    "method":"ANY"
   },
  "response":{
     "body":"{{jsonbody response.body '$.details.[full.name]'}}"
  }
}

Error:
------
Error 500 wiremock.com.google.common.util.concurrent.UncheckedException: wiremock.com.github.jknack.handlebars.HandlebarsException: inline@26d6cbba:1:3: count not find helper: &apos;jsonpath&apos;....

**Comment by tomakehurst** [comment]
Handlebars requires you to quote keys containing metacharacters:

```handlebars
{{jsonPath request.body '$.details.[\'full.name\']'}}
```
