### ISSUE TITLE
Question: Saving mappings as files

### ISSUE THREAD

**Issue by NewbieProger** [wiremock/wiremock#1947]
Hello. 

When I have set wiremock's recording mappings I noticed, that I send my json-mappings via API and I cant find'em as files in home/wiremokc, but I see recorded mappings with proxing feature. 

Now, I have a question: where my mappings store? Is difference how it stores when we are sending it via API, or mount it as volumes?

**Comment by tomakehurst** [comment]
Hey @NewbieProger please post questions to the mailing list as per the instructions. We try to keep issues for bugs and feature requests.
