### ISSUE TITLE
Shadowing slf4j-api 2.x without changing package name causes issues in projects that are on 1.x

### ISSUE THREAD

**Issue by jonatan-ivanov** [wiremock/wiremock#1964]
It seems the latest version of `wiremock-jre8-standalone` (`2.34.0`) shadows `slf4j-api` 2.x (`api "org.slf4j:slf4j-api:2.0.1"`) without changing its package name.

This means that if a project uses `slf4j-api` 1.x, they will have two versions of slf4j on their classpath: 1.x because they intentionally depend on slf4j 1.x and 2.x (unintentionally) because of `wiremock-jre8-standalone` so the slf4j 2.x classes can be loaded by the classloader instead of 1.x (what the project actually want to use) causing issues.
See related issue in Micrometer: https://github.com/micrometer-metrics/micrometer/issues/3414

I saw this in the issue guidelines:
>Please do not log bugs regarding classpath issues...

and also read the comments of https://github.com/wiremock/wiremock/issues/1424 but I feel projects using `wiremock-jre8-standalone` and `org.slf4j:slf4j-api:1.+` should be a valid use-case. Maybe slf4j should be fixed so that it can be shadowed properly or wiremock could use an internal logging component that can delegate to slf4j?

**Comment by clemstoquart** [comment]
Not sure what's the right move here but some major framework like Spring are moving to `slf4j` 2.x. So it might just be a temporary issue.

**Comment by tomakehurst** [comment]
The obvious fix here seems to be roll back to slf4j 1.7.x, but if newer Spring releases now use 2.0.x then presumably we'll just start seeing the same problem there?

I guess it might be possible to remove it completely, aside from as a compile-only dependency.

**Comment by jonatan-ivanov** [comment]
Newer Spring releases brings in 2.x but in that case, I think the Spring BOM should dictate the version so the users are aware that they use 2.x and they will also get a matching implementation (i.e.: logback) version that supports both 1.x and 2.x. I think in that case, this should be a slightly smaller issue since the implementation (logback) should support both versions.

**Comment by tomakehurst** [comment]
Removing slf4j-api from the standalone JAR completely breaks it, so this isn't an option.

I think we need to do one of the following, would appreciate feedback:

1) Rewrite the slf4j-api package name so that it doesn't clash. Downside is that you then can't enable logging from libraries that WireMock depends on (not sure this is a particularly big deal).
2) Drop back to 1.x per #1965.
3) (Nuclear option) start releasing separate a standalone (for running as a process) and fat (for use as a library) JAR  where the latter has a POM dependency on slf4j, which can therefore be overridden in your own dependencies.

@SingingBush Sadly JPMS won't solve this in the short term because we're keeping Java 8 support until the end of 2.x.

**Comment by clemstoquart** [comment]
Hello,

In my humble opinion, we should stick with SLF4J 1.7.x  in the 2.x branch like that there's no breaking change.

In the meantime I think that moving to SLF4J 2.x should happen with the Wiremock 3.x release. Conservative users will have to stick with Wiremock 2.x until they're ready to move to SLF4J 2.x.

**Comment by tomakehurst** [comment]
Seems like we're going to break somebody either way - users with 2.x in their dependencies might end up with 1.7.x from WireMock taking precedence or vice versa. But there might be fewer who experience issues in the short term with 1.7.x so I sympathise.

I am actually leaning quite strongly towards relocating it, as really the only use case I think of for enabling logging in WM's dependencies is HTTP client wire logging, which we can find an alternative for if necessary.

**Comment by tomakehurst** [comment]
OK, going with option 1 for the next (and hopefully final this time) 2.x release.

Will revisit, probably with a view to upgrading to 2.x of slf4j in WireMock 3.x.

**Comment by pkoenig10** [comment]
@tomakehurst Could we make a new 2.x release with this fix?
