### ISSUE TITLE
Jetty 10 support

### ISSUE THREAD

**Issue by reta** [wiremock/wiremock#1967]
The Jetty 10 is the next (last?) `javax.*` compatible release branch: JDK 11 base line, new APIs. It woud be great to have `wiremock` to support Jetty 10, along with Jetty 9 (and Jetty 11 [1]).

@tomakehurst wdyt? Once we done with Jetty 11 [1], we could also work on supporting Jetty 10, preferably alongside with Jetty 9, so `wiremock` could be used in wider range of applications (should be easier at least with respect to `fileupload`).     

[1] https://github.com/wiremock/wiremock/issues/1760

**Comment by tomakehurst** [comment]
I feel like this probably won't be worth the amount of noise and support headaches this will cause, especially since Jetty 10 is also JVM 11+.

**Comment by tomakehurst** [comment]
What would be more interesting is a build that uses the in-built Java HTTP client and server rather than Jetty + Apache.

**Comment by tomakehurst** [comment]
Agreed it wouldn't support everything that Jetty can, but a large proportion of WireMock's use is plain HTTP/1.1, without faults, HTTP/2 or any of the more advanced features.

Being able to support the majority cases with a dependency-light version could still be very useful.

**Comment by oleg-nenashev** [comment]
@tomakehurst AFAICT it is in the scope for WireMock 3.0, because Jetty 11 support is already in the codebase. Please correct me if I am wrong

**Comment by oleg-nenashev** [comment]
FTR https://github.com/wiremock/wiremock/issues/1760

**Comment by tomakehurst** [comment]
Yep, this is now obsolete.

**Comment by natan-abolafya** [comment]
Hi there. Just wanted to comment for visibility.
We are migrating our application to jetty 10 from 9 right now (dropwizard 2->3). It is kind of a middle step so the changes are smaller. We'll probably go to jetty 11 some time later.

But now we can use neither wiremock 2 nor 3 as the jetty versions don't match and the dependencies pulled don't align.
Do you have any tips to work around this?

**Comment by reta** [comment]
> Do you have any tips to work around this?

@natan-abolafya the workaround that works for us is to use `wiremock-jre8-standalone`

**Comment by jluehe** [comment]
> > Do you have any tips to work around this?
> 
> @natan-abolafya the workaround that works for us is to use `wiremock-jre8-standalone`

@reta, could you please elaborate a bit? Thanks a lot!

**Comment by jluehe** [comment]
@reta, is migrating from `wiremock-jre8` to `wiremock-jre8-standalone` supposed to be a drop-in replacement? When I do that, existing code fails to compile with this error:

`The method withJsonBody(wiremock.com.fasterxml.jackson.databind.JsonNode) in the type ResponseDefinitionBuilder is not applicable for the arguments (com.fasterxml.jackson.databind.JsonNode)`

It looks like `ResponseDefinitionBuilder.withJsonBody` now expects an argument of the **_shaded_** `com.fasterxml.jackson.databind.JsonNode` type?
