### ISSUE TITLE
Finding a free port automatically

### ISSUE THREAD

**Issue by vertti** [wiremock/wiremock#205]
Would be nice to have Wiremock rule find free port automatically, for example by giving port number 0. Use case: we have jenkins running multiple microservices builds concurrently, managing different ports for each manually is a small nuisance.

**Comment by posto** [comment]
would be nice to have this documented
stumbled upon this by mistake and was looking exactly for such a thing

**Comment by tomakehurst** [comment]
All will be revealed when 2.0 comes out of beta :-)

Meanwhile, if you want to browse the 2.0 docs:
https://github.com/tomakehurst/wiremock/blob/2.0-beta/docs/source/getting-started.rst
