### ISSUE TITLE
matching multiple XPath expresions

### ISSUE THREAD

**Issue by freakabcd** [wiremock/wiremock#206]
Is it possible to chain multiple matchingXPath expressions? I want to determine if the XML request/response has certain elements (some needing to match content/attrs as well).

**Comment by HARIKRISHNAPALEMPATI** [comment]
I am also trying to do the same but through Json configuration.
"bodyPatterns" : [
          {
              "matchesXPath" : 
                  "SOAP-ENV:Envelope/SOAP-ENV:Body/report:name//report:First[text()='test']",
              "xPathNamespaces" : {
                  "SOAP-ENV" : "http://schemas.xmlsoap.org/soap/envelope/",
                  "report" : "http://schemas.xmlsoap.org/soap/env/"
              }
          }
      ]

It is working fine. But I have to give multiple matching criteria.
Will matchesXPath accepts array?

"bodyPatterns" : [
          {
              "matchesXPath" : {
                  "SOAP-ENV:Envelope/SOAP-ENV:Body/report:name//report:First[text()='cent']",
                  "SOAP-ENV:Envelope/SOAP-ENV:Body/report:name//report:Last[text()='joe']"
              },
              "xPathNamespaces" : {
                  "SOAP-ENV" : "http://schemas.xmlsoap.org/soap/envelope/",
                  "report" : "http://schemas.xmlsoap.org/soap/env/"
              }
          }
      ]

It is not working.

**Comment by Rafayel93** [comment]
You can try by this way.
{
"matchesXPath" : "//MsgID[contains(text(),'ex1')] | //MsgID[contains(text(),'ex2')] "
}
