### ISSUE TITLE
Feature request: a way to disable admin API endpoint "/__admin"

### ISSUE THREAD

**Issue by max-rocket-internet** [wiremock/wiremock#2062]
We use wiremock in standalone mode with JSON files for configuration. Sometimes we need to have wiremock available on a public endpoint so for obvious security reasons we would like to have a way to disable the admin API endpoint completely.

For example, adding a `--disable-admin-api` command line argument.

Or is there another solution already available to achieve this?

**Comment by owenkim** [comment]
Had a similar question. I couldn't find if there was a way to disable it but there appears to be an undocumented command-line option to set Basic Auth on the Admin API.

https://github.com/wiremock/wiremock/blob/3.2.0/src/main/java/com/github/tomakehurst/wiremock/standalone/CommandLineOptions.java#L99

**Comment by Gawne** [comment]
+1

**Comment by leeturner** [comment]
Hi, there isn't currently a way to disable the admin endpoints but as @owenkim mentioned, you can protect them via basic auth.  It looks like we missed adding that to the documentation so I will add that

**Comment by leeturner** [comment]
Just as a quick example before I sort out the docs.  You can start WireMock with the following flag `--admin-api-basic-auth` passing you username and password in the standard format - `username:passord`:
```
java -jar wiremock-standalone-3.9.1.jar --admin-api-basic-auth my-username:my-super-secret-password
```
Any call made to the admin API after that will need the correct `Authorization` header passed or a `401` will be returned.

**Comment by leeturner** [comment]
Hi, this has now been documented here - https://wiremock.org/docs/standalone/java-jar/#securing-the-wiremock-admin-api

I will close this issue if everyone is happy with this solution ?

**Comment by Gawne** [comment]
Brilliant stuff - we've implemented in our internally hosted service. Thanks for the speedy response.

**Comment by Gawne** [comment]
happy for you to close issue
