### ISSUE TITLE
get a value by a key from request.query that contains a dot

### ISSUE THREAD

**Issue by El-kady** [wiremock/wiremock#2074]
what i'am trying to to is to get a value from URL params, but this value contains dots "product.productCharacteristic.value"

`{
    "request": {
        "urlPath": "/exampleOfPath",
        "method": "GET",
        "queryParameters": {
            "product.productCharacteristic.name": {
                "equalTo": "MSISDN"
            },
            "product.productCharacteristic.value": {
                "matches": ".*"
            }
        }
    },
    "response": {
        "status": 200,
        "jsonBody": {
            "key": "the value should be here {{request.query['product.productCharacteristic.value']}}"
        },
        "transformers": [
            "response-template"
        ],
        "headers": {
            "Content-Type": "application/json"
        }
    }
}`

i have tested all of those

- {{request.query.['product.productCharacteristic.value']}}
- {{request.query['product.productCharacteristic.value']}}
- {{request.query['product%2EproductCharacteristic%2Evalue']}}
- {{request.query.['product%2EproductCharacteristic%2Evalue']}}
- {{request.query.product%2EproductCharacteristic%2Evalue}}
- {{request.query.product.productCharacteristic.value}}
- {{lookup request.query 'product.productCharacteristic.value'}}
- {{lookup request.query 'product%2EproductCharacteristic%2Evalue'}}

**Comment by Mahoney** [comment]
Closing as this was answered here:
https://stackoverflow.com/questions/75276500/wiremock-request-query-not-working-with-a-paramter-that-contains-dots
