### ISSUE TITLE
Relocate Jackson in webhooks extension

### ISSUE THREAD

**Issue by mcassidygamma** [wiremock/wiremock#2080]
In the webhooks extension, please can the shaded dependencies for jackson be relocated (they are already in the standalone JAR). This will prevent clashes with projects that already use Jackson but need to use a different version. Thanks.

**Comment by oleg-nenashev** [comment]
If Jackson is shaded, how there could be a conflict @mcassidygamma?

**Comment by tomakehurst** [comment]
Obsolete now that webhooks is in the core
