### ISSUE TITLE
Result (emptyJson) returned immediately without being stored in a variable, if any

### ISSUE THREAD

**Issue by Funtic** [wiremock/wiremock#2085]
https://github.com/wiremock/wiremock/blob/25b82f9f97f3cc09136097b249cfd37aef924c36/src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/ParseJsonHelper.java#L60

Result (emptyJson) returned immediately without being stored in a variable, if any

**Comment by tomakehurst** [comment]
Can you elaborate a bit? In what context does this cause a problem?

**Comment by Funtic** [comment]
@tomakehurst  {{parseJson '{}' 'emptyObject'}} prints {} instead of storing empty hashmap to 'emptyObject' variable

**Comment by tomakehurst** [comment]
Ah, I see.

Feel like raising a PR to fix?

**Comment by G-Basak** [comment]
@Funtic @tomakehurst , please let me know whether https://github.com/wiremock/wiremock/pull/2277 satisfies the requirement.
