### ISSUE TITLE
Filtering ServeEvents

### ISSUE THREAD

**Issue by NewbieProger** [wiremock/wiremock#2098]
Hi. How to filter ServeEvents, if I want to delete all requests matches to RequestPattern?

**Comment by bmarwell** [comment]
You cannot undo events which already happened. You can use Java streams to filter them into a new list. Is this what you want to do?

**Comment by tomakehurst** [comment]
Hey @NewbieProger to get support please can you head over to the community Slack rather than opening GH issues?
