### ISSUE TITLE
Can't execute standalone example from docs

### ISSUE THREAD

**Issue by colpachoque** [wiremock/wiremock#210]
Hi, Tom!

I am newbie and I can't run the example from docs. I just started server using  "java -jar wiremock-1.52-standalone.jar". It is all ok. Then, in another cmd window I type "curl -X POST --data '{ "request": { "url": "/get/this", "method": "GET" }, "response": { "status": 200, "body": "Here it is!\n" }}' http://localhost:8080/__admin/mappings/new" as in the example.
But there is an error:

C:\WINDOWS\system32>curl -X POST --data '{"request":{"url":"/get/this","method":
"GET"},"response":{"status":200,"body":"Here it is!\n"}}' http://localhost:8080/
__admin/mappings/new
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 Unable to bind JSON to object. Reason: Unexpected character (''
' (code 39)): expected a valid value (number, String, array, object, 'true', 'fa
lse' or 'null')
 at [Source: '{request:{url:/get/this,method:GET},response:{status:200,body:Here
 it is!\n}}'; line: 1, column: 2]  JSON:'{request:{url:/get/this,method:GET},res
ponse:{status:200,body:Here it is!\n}}'</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /__admin/mappings/new. Reason:
<pre>    Unable to bind JSON to object. Reason: Unexpected character (''' (code
39)): expected a valid value (number, String, array, object, 'true', 'false' or
'null')
 at [Source: '{request:{url:/get/this,method:GET},response:{status:200,body:Here
 it is!\n}}'; line: 1, column: 2]  JSON:'{request:{url:/get/this,method:GET},res
ponse:{status:200,body:Here it is!\n}}'</pre></p><h3>Caused by:</h3><pre>java.la
ng.RuntimeException: Unable to bind JSON to object. Reason: Unexpected character
 (''' (code 39)): expected a valid value (number, String, array, object, 'true',
 'false' or 'null')
 at [Source: '{request:{url:/get/this,method:GET},response:{status:200,body:Here
 it is!\n}}'; line: 1, column: 2]  JSON:'{request:{url:/get/this,method:GET},res
ponse:{status:200,body:Here it is!\n}}'
        at com.github.tomakehurst.wiremock.common.Json.read(Json.java:33)
        at com.github.tomakehurst.wiremock.stubbing.StubMapping.buildFrom(StubMa
pping.java:56)
        at com.github.tomakehurst.wiremock.admin.NewStubMappingTask.execute(NewS
tubMappingTask.java:27)
        at com.github.tomakehurst.wiremock.http.AdminRequestHandler.handleReques
t(AdminRequestHandler.java:55)
        at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(Ab
stractRequestHandler.java:38)
        at com.github.tomakehurst.wiremock.jetty6.Jetty6HandlerDispatchingServle
t.service(Jetty6HandlerDispatchingServlet.java:97)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at wiremock.org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder
.java:511)
        at wiremock.org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandl
...

Please, help me do it properly

**Comment by JeevFresno** [comment]
Hi,

I am running into the same problem Did you figure it out what was causing the problem?

thanks
