### ISSUE TITLE
PUT stub seems to fail if test method runs too fast

### ISSUE THREAD

**Issue by rotilho** [wiremock/wiremock#2108]
## Bug reports

Stub a put method intermittently makes test to fail. This issue was long discussed in https://github.com/wiremock/wiremock/issues/97 and there're few known workarounds but it would be great to get it fixed.

How to reproduce?

Normally I see this issue happening in (slow) CI/CD instances and almost never happens locally. To try to reproduce you need to have multiple tests stubbing an put endpoint.

I.E.:
```
        stubFor(put(urlEqualTo("/example-endpoint"))
                .willReturn(
                       ok()
                )
        );
```

Version: 2.35.0

**Comment by tomakehurst** [comment]
So repeatedly running a test that just adds the stub you've shown causes the failure?

Can you share a bit more detail - Java version, platform, how you're running the tests and the error you're seeing?

**Comment by rotilho** [comment]
I was under the impression that repeat the test was enough but I'm struggling to reproduce it in a minimal example.

I'll resume it later.

**Comment by rotilho** [comment]
I couldn't reproduce in a minimal example. Closing it...
