### ISSUE TITLE
Beta: Support Externalized State

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock#2144]
### Proposal

It would be nice to support externalized state for WireMock instance so that it is the service runtime could be stopped and restarted on-demand. It could be an extension point that could connect different databases, file storages or public cloud services based on the implementation

As @tomakehurst , it is already mostly done in WireMock 3.x

### Scope

- [x] Implementation
- [ ] Verification and testing
- [ ] Maybe - Load load testing
- [ ] Documentation

**Comment by oleg-nenashev** [comment]
As we agreed, this API needs to annotated as Beta as a part of #2153

**Comment by tomakehurst** [comment]
Added in beta form in the 3.0.0 GA release

**Comment by ascopes** [comment]
@oleg-nenashev / @tomakehurst hello... got a small question on the implementation of the Store interfaces introduced by this change.

There is an operation `getAllKeys()` which returns a `Stream<K>`.

In my case, I'm looking to use a `scan` within Redis to yield these results, with some logic to batch them up to avoid loading large amounts of data into memory. However, I have to be sure to return the Redis client I am using back to an object pool once I have finished with it.

Is there any guarantees that the stream that I return will always be used within the context of a try-with-resources such that it is explicitly disposed of in all cases once no longer needed, or is this something I need to load fully into memory to avoid leaking resources?

**Comment by tomakehurst** [comment]
@ascopes can I suggest moving this discussion to its own issue?

As of now, this stream returned by this method is consumed only via `count()` and `collect(...)` in the Java streams APIs, which  I assume have robust exception handing and termination, but WireMock itself does not add any guarantees of its own.
