### ISSUE TITLE
Data Provider extension point

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock#2145]
### Proposal

Currently it is possible to source data only from external file on the filesystem. It would be great to add more capabilities there, especially for public cloud and Kubernetes deployments

Usage Examples:

- Data from a blog storage like S3
- Data from a Kubernetes Custom Resource Definition (e.g. for operator use-cases)
- Custom implementation, e.g. data from a JAR resources
- ...

The extension point should be usable in WireMock extensions that are expected tio bundle all necessary dependencies for its implementation

**Comment by kapishmalik** [comment]
@oleg-nenashev  @tomakehurst I would really want to explore and work on this request post GraphQL request.

**Comment by tomakehurst** [comment]
Added in ea6a9a6b347350514f533ec9d7b0a40dedd409c1
