### ISSUE TITLE
Add healthcheck endpoint to WireMock Standalone

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock#2164]
### Proposal

When running WireMock as a standalone instance, e.g. as a part of WireMock Docker, it would be nice to have a have a built-in Health Check endpoint that checks the status of WireMock and returns error wuth defaults when WireMock Server is considered malfunctional and not ready to serve Mock APIs.

**Comment by julian-michelmann** [comment]
I would like to have a look at this. 

So far, I have found two PRs, one open and one closed, on this topic. 
https://github.com/wiremock/wiremock/pull/1730
https://github.com/wiremock/wiremock/pull/958

The open one, nothing has happened there for a while, and I think it's abandoned. There is also a related issue: 
https://github.com/wiremock/wiremock/issues/1339

There is a comment in the closed PR: 
"This is a nice idea, but it doesn't need to be a core feature now that it's possible to add API routes via extensions.
Can I suggest you spin this out into a separate project?"

Since it's from 2008, and I don't see the point of not having this as a feature, I want to create my PR based on the other two attempts if there's no objection.

**Comment by efenderbosch** [comment]
Google led me here, I'm just using this
```yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider -O /dev/null localhost:8080/__admin/mappings" ]
```
Anything wrong/missing with this?

**Comment by oleg-nenashev** [comment]
@efenderbosch Yes it is what you can do at the moment. But it has certain weaknesses:

* It checks whether the endpoint works, not whether WireMock is operational as whole (e.g. serving mock APIs in processing thread pool). So it is just a smoke test
* It does not return basic health metrics in the response. These metrics would be useful for troubleshooting

**Comment by tomakehurst** [comment]
Things have moved on since 2018 and I agree this is reasonable to have as a core feature so I suggest we go ahead and create a fresh PR. @julian-michelmann if you're happy to do this it would be much appreciated.

It'd be nice to be able to get version info from a standard endpoint too, although I suspect it's better practice to put that somewhere separate - what do we think?

**Comment by oleg-nenashev** [comment]
Sorry @julian-michelmann I missed the comment here. I would definitely follow this approach and build it atop of one of the pull requests you mentioned.  With the Docker container being official, I believe the basic healthcheck should be a part of the core and maybe support its own extensibility in the future

**Comment by ikalu** [comment]
@tomakehurst and @oleg-nenashev - I just created a PR for this feature - #[2303](https://github.com/wiremock/wiremock/pull/2303) 

Please take a look and let me know if you have any suggestions.

**Comment by wallid** [comment]
This would be good as wait strategy for test containers. Is there any logs to use?

**Comment by oleg-nenashev** [comment]
@wallid Yep, we're working on it and I hope to get something before WireMock 3.0
Indeed the current status is super annoying for Testcontainers startup:
ofc We could have an extension but it is better to be a part of WireMock core

```
15:24:44.373 [main] INFO  tc.wiremock/wiremock:2.35.0 - Creating container for image: wiremock/wiremock:2.35.0
15:24:44.937 [main] INFO  tc.wiremock/wiremock:2.35.0 - Container wiremock/wiremock:2.35.0 is starting: 436ec120966b8e132f820939e1352e9ef01122437930a5a0c124c15fb61838ea
15:24:45.449 [main] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /crazy_leavitt: Waiting for 60 seconds for URL: http://localhost:51735/__admin/mappings (where port 51735 maps to container port 8080)
15:24:46.379 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDOUT: WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
15:24:47.971 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR: Exception in thread "main" com.github.tomakehurst.wiremock.standalone.MappingFileException: Error loading file /home/wiremock/./mappings/json-body-transformer.json:
15:24:47.972 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR: Unrecognized token 'WireMockContainerExtensionTest': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
15:24:47.972 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR:  at [Source: (String)"WireMockContainerExtensionTest/json-body-transformer.json"; line: 1, column: 31]
15:24:47.973 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR: 	at com.github.tomakehurst.wiremock.standalone.JsonFileMappingsSource.loadMappingsInto(JsonFileMappingsSource.java:126)
15:24:47.973 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR: 	at com.github.tomakehurst.wiremock.core.WireMockApp.loadMappingsUsing(WireMockApp.java:224)
15:24:47.974 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR: 	at com.github.tomakehurst.wiremock.core.WireMockApp.loadDefaultMappings(WireMockApp.java:220)
15:24:47.974 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR: 	at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:112)
15:24:47.974 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR: 	at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:70)
15:24:47.974 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR: 	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:62)
15:24:47.974 [docker-java-stream--1570438987] INFO  org.wiremock.integrations.testcontainers.WireMockContainerExtensionTest - STDERR: 	at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.main(WireMockServerRunner.java:133)

```

**Comment by mmcedora** [comment]
Any update on this? Would be a great feature for increased reliability and debuggability

**Comment by tomakehurst** [comment]
This should be closed. Was added in e6af9264f79c2717664e73365bdd7d09439db425 and is released in the latest version.

**Comment by mmcedora** [comment]
Great, but might the docker image for wiremock lack a "healtcheck configuration in the dockerfile" that calls into the new healthcheck endpoint.

**Comment by tomakehurst** [comment]
No, this issue is just about adding it to WireMock itself, it hasn't been integrated into the official Docker image yet.

We'd be happy to accept a PR in https://github.com/wiremock/wiremock-docker for this if you feel like creating one.
