### ISSUE TITLE
Recent releases are not available on Maven central

### ISSUE THREAD

**Issue by matsev** [wiremock/wiremock#2189]
### Proposal

Please make sure that recent releases of wiremock are published on Maven central. 

Group id: `com.github.tomakehurst`

Artifact ids:
- `wiremock`
- `wiremock-standalone`

Missing versions:

- `2.35.0`
- `2.34.0`
- `2.33.2`
- `2.33.1`
- `2.33.0`
- `2.32.0`
- `2.31.0`
- `2.30.0`
- `2.29.1`
- `2.29.0`
- `2.28.1`
- `2.28.0`

(plus some beta releases)

### Reproduction steps

Add the following configuration to your pom file, where `[ver]` is one of the missing versions stated above:

```
<dependency>
    <groupId>com.github.tomakehurst</groupId>
    <artifactId>wiremock-standalone</artifactId>
    <version>[ver]</version>
    <scope>test</scope>
</dependency>
```

Execute `mvn test` and observe download attempt of the specified artifact failing. Similarly, download will also fail if the `<artifactId>` is replaced with one of the other wiremock artifacts. 

### References

references:
https://mvnrepository.com/artifact/com.github.tomakehurst/wiremock
https://central.sonatype.com/artifact/com.github.tomakehurst/wiremock/3.0.0-beta-8/versions

### Comment

The corresponding version numbers exists for [wiremock-jre8](https://central.sonatype.com/artifact/com.github.tomakehurst/wiremock-jre8/2.35.0/versions) and [wiremock-jre8-standalone](https://central.sonatype.com/artifact/com.github.tomakehurst/wiremock-jre8-standalone/2.35.0/versions) artifacts.

**Comment by oleg-nenashev** [comment]
There is some confusion because of the artifactId. 

Please follow the guidelines here:

- Recent 2.x releases, note the `-jre8` suffix is used: https://wiremock.org/docs/download-and-installation/
- 3.x beta: https://wiremock.org/3.x/docs/download-and-installation/ 

So IMHO not a defect but definitely DevX and documentation could be improved

**Comment by oleg-nenashev** [comment]
I will definitely keep it for the docs matters

**Comment by joseph-so** [comment]
Hi @oleg-nenashev ,
   Version 3 is not available on Maven since v3 beta-11 
    https://mvnrepository.com/artifact/com.github.tomakehurst/wiremock 
   Thanks
Joseph

**Comment by oleg-nenashev** [comment]
@joseph-so please see https://github.com/wiremock/wiremock/releases/tag/3.0.0-beta-11. A new Maven group ID is used going forward

**Comment by joseph-so** [comment]
@oleg-nenashev thanks. Is it possible to update the website about the new ID?

**Comment by joseph-so** [comment]
@oleg-nenashev thanks

**Comment by oleg-nenashev** [comment]
The documentation was updated last week : https://github.com/wiremock/wiremock.org/pull/134 , https://github.com/wiremock/wiremock.org/pull/135
