### ISSUE TITLE
Cannot deserialize Stubmapping due to conflicting setter definition for property "postServeActions"

### ISSUE THREAD

**Issue by dirkbolte-jb10x** [wiremock/wiremock#2221]
### Proposal

Wiremock version: `3.0.0-beta-9`
Jackson version: `2.15.2`

I want to add a new stub mapping to wiremock programmatically - I have to provide a different Spring Rest Controller which forwards the stub mapping to the wiremock server.  As the `StubMapping` class already has JSON annotations, I used this as `RequestBody`, letting Jackson do all the parsing. Unfortunately, it fails due to an `InvalidDefinitionException`: `Conflicting setter definitions for property "postServeActions": com.github.tomakehurst.wiremock.stubbing.StubMapping#setPostServeActions(java.lang.Object) vs com.github.tomakehurst.wiremock.stubbing.StubMapping#setPostServeActions(java.util.List)`

The body I'm sending is matching a body I'm using in another part of my code with `loadMappingsUsing`, so the definition in itself seems correct.

I was able to create a minimal reproduction as unit test resulting in the same error (see `Reproduction steps`).

### Reproduction steps

```java
import com.fasterxml.jackson.databind.ObjectMapper;
import com.github.tomakehurst.wiremock.stubbing.StubMapping;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

public class WiremockTest {

    private final ObjectMapper mapper = new ObjectMapper();

    @Test
    void testParsing() {
        var request = Map.of("request", Map.of(), "response", Map.of());

        assertDoesNotThrow(() -> mapper.readValue(mapper.writeValueAsString(request), StubMapping.class));
    }
}
```

**Comment by dirkbolte-jb10x** [comment]
FYI: parsing works fine when using `com.github.tomakehurst.wiremock.common.Json#getObjectMapper()`

**Comment by dirkbolte-jb10x** [comment]
Probably an uncommon one as the setter is in there for a longer time. Anyhow: would it be ok for me to submit a PR?

**Comment by tomakehurst** [comment]
What fix did you have in mind?

Will it involve a breaking change to the API?

**Comment by dirkbolte-jb10x** [comment]
What I would try it to merge both setters and add one `instanceof` . This shouldn't be a breaking change.

**Comment by tomakehurst** [comment]
Happy to merge this in that case.

**Comment by dirkbolte** [comment]
sry, PEBKAC. Wasn't able to reproduce it in the wiremock code base and then figured that the the only showed up when working with the standalone version (which I had for whatever reason used in my project).
