### ISSUE TITLE
Load multiple json response via java

### ISSUE THREAD

**Issue by csraju1980** [wiremock/wiremock#2230]
### Proposal

How to import multiple stub json files? When i run below command i can only see one stub file. But i want load multiple stub files via java please advise

http://localhost:8080/__admin/mappings

### Reproduction steps

http://localhost:8080/__admin/mappings/imports are also failing with below error

{
    "errors": [
        {
            "code": 10,
            "source": {},
            "title": "Error parsing JSON",
            "detail": "Unexpected character ('-' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value\n at [Source: (String)\"----------------------------208472049742120374679453\r\nContent-Disposition: form-data; name=\"file\"\r\n\r\nCreateAccessDomainSucces.json\r\n----------------------------208472049742120374679453--\r\n\"; line: 1, column: 3]"
        }
    ]
}

**Comment by tomakehurst** [comment]
Please post questions/help requests to the community Slack or Stackoverflow
