### ISSUE TITLE
Publish WireMock 3.x to org.wiremock Maven group ID

### ISSUE THREAD

**Issue by tomakehurst** [wiremock/wiremock#2237]
### Proposal

Switch all future publication to org.wiremock

**Comment by pks-1981** [comment]
@tomakehurst 
Wow!
Packages will be renamed?

**Comment by tomakehurst** [comment]
Not the Java packages, just the Maven group ID.

We're not total sadists 😄

**Comment by oleg-nenashev** [comment]
> Not the Java packages, just the Maven group ID.
> We're not total sadists 😄

I am not a sadist, and I survived Apache HTTP Client 4.x and 5.x. So maybe we should try? :P 
Speaking seriously, it would make sense to start using new group IDs for chunks like the extension API you're working on @tomakehurst . Would work well with public accessibility annotations

**Comment by rafalh** [comment]
@tomakehurst shouldn't this be closed? I can see that there are already two new version published under new group that are not available using old group.

**Comment by oleg-nenashev** [comment]
FTR it was changed in 3.0.0-beta-11 by https://github.com/wiremock/wiremock/commit/ee1363c404faa54ce83ddb552bf3c241763b5fff. It was a direct push so the changelog drafter didn't capture it. Updated the changelog

https://github.com/wiremock/wiremock.org/issues/131 for the downstream docs patches
