### ISSUE TITLE
IntelliJ run configurations

### ISSUE THREAD

**Issue by picimako** [wiremock/wiremock#2273]
### Proposal

The WireMock [contribution guide](https://github.com/wiremock/wiremock/blob/master/CONTRIBUTING.md) mentions a few Gradle commands that are necessary for different aspects of developing WireMock itself.

Each such command could have a specific IntelliJ Run Configuration added to the repository, so that contributors have easier and quicker access to these actions, something like the ones below:

| Command | Run Configuration name |
|---|---|
| `./gradlew clean test` | Run tests |
| `./gradlew jar shadowJar`  | Build WireMock |
| `./gradlew publishToMavenLocal` | Publish to Maven local |
| `./gradlew spotlessApply` | Run Spotless |

**Comment by oleg-nenashev** [comment]
It would be nice indeeed

**Comment by picimako** [comment]
Alright. Then, I'll create a PR for this soon.

**Comment by oleg-nenashev** [comment]
@picimako I guess it can be closed now, right?

**Comment by picimako** [comment]
@oleg-nenashev Yes, it is completed and can be closed.
