### ISSUE TITLE
Proposal: change Queue on to Deque in InMemoryRequestJournalStore

### ISSUE THREAD

**Issue by pks-1981** [wiremock/wiremock#2296]
### Proposal

private final Queue<UUID> queue = new ConcurrentLinkedQueue<>(); 
->
private final Deque<UUID> queue = new ConcurrentLinkedDeque<>();

Change the add and remove methods.
queue.poll(); -> queue.pollLast();
queue.add(event.getId()); -> queue.addFirst(event.getId());

As a result, there will be no need to make a copy and reverse it.
ImmutableList.copyOf(store.getAll().collect(toList())).reverse();

**Comment by pks-1981** [comment]
@tomakehurst What do you think?

**Comment by tomakehurst** [comment]
This sounds good to me. I've never liked reversing the queue when serving it back, but I'd never got around to figuring out the best way to avoid it.

**Comment by pks-1981** [comment]
@tomakehurst @oleg-nenashev 
plz add Breaking change label
