### ISSUE TITLE
Error parsing JSON with Delay value

### ISSUE THREAD

**Issue by Fr3di** [wiremock/wiremock#2301]
### Proposal

Wiremock Studio 2.35.0-1

I have a PATCH stub with delay value. When I change the return status code, and try to save changes, it throws below error:
```
Error parsing JSON
Unrecognized field "lower" (class com.github.tomakehurst.wiremock.http.FixedDelayDistribution), not marked as ignorable
```

This happens in any kind of delay, not only fixed one.

Current behavior:
- Not able to save changes until changing the Delay to any other kind and back, and set the value again

Expected behavior:
- Save changes without any issues

### Reproduction steps

1. Create a STUB and set Response status to 200
2. Set Delay to Fixed and add some value i.e. 3000
3. Click Save button
4. Change Response status to 404
5. Click Save button - you should see the error

**Comment by oleg-nenashev** [comment]
Hello @Fr3di . WireMock Studio is a deprecated proprietary project, and it is not supported by the community. Please reproduce the issue with WireMock 2.35 or, preferably, 3.x Beta
