### ISSUE TITLE
Enhancement Request: Adding Flexibility to MappingsSource Implementation

### ISSUE THREAD

**Issue by bharatnpti** [wiremock/wiremock#2331]
### Proposal

**Background:**
Currently, WireMock features a single implementation of MappingsSource known as JsonFileMappingsSource. This implementation is responsible for loading mappings exclusively from the .mappings directory.

**Proposal:**
It's not uncommon for users or projects to require loading mappings from alternative sources such as Git repositories, databases, and more. However, as things stand, making such changes to accommodate different sources necessitates cloning the WireMock repository, introducing modifications, and maintaining a separate codebase.

**Enhancement Idea:**
I propose introducing a command-line option specifically for standalone usage. This option would enable users to specify their preferred MappingsSource implementation, thus making it easier to load mappings from diverse sources without the need for significant code alterations.

**Benefits**:
The inclusion of this feature would offer the open-source community a streamlined way to contribute various implementations of MappingsSource. This could involve sources like Git repositories, databases, and more. By submitting pull requests with these alternative implementations, contributors would empower the community to customize WireMock's behavior to better suit different use cases.

**How to Proceed:**
I kindly request guidance from the WireMock maintainers on the feasibility of this enhancement. If it aligns with the project's goals, would be enthusiastic about contributing to its implementation. Your feedback on the technical approach, potential challenges, and any recommended modifications would be greatly appreciated.

**Comment by tomakehurst** [comment]
Hi @bharatnpti the `MappingsSource` implementation is already pluggable via the `Options` object passed to the WireMock server on startup so it's not necessary to fork the code to achieve this.

However, it's not exposed as an extension point right now meaning that you have to build your own fat JAR if you want to run standalone.

I would suggest starting to solve this problem by allowing the `MappingsSource` (or maybe even more than one) impl to be loaded as an extension.

**Comment by bharatnpti** [comment]
Hi @tomakehurst,

I have raised PR following your suggestion. Can you please review - https://github.com/wiremock/wiremock/pull/2334
