### ISSUE TITLE
Scenarios unexpectedly play back in reverse order

### ISSUE THREAD

**Issue by btrautmann** [wiremock/wiremock#2364]
### Proposal

**Expected behavior:** When recording a series of identical requests with the default `repeatsAsScenarios` setting (`true`), playing _back_ the scenario after recording has been stopped should play back the responses in the same order they were recorded.

**Actual behavior:** When recording a series of identical requests with the default `repeatsAsScenarios` setting (`true`), playing _back_ the scenario after recording has been stopped plays back the scenario in _reverse_ order. In other words, the mapping that _completes_ the scenario is incorrectly configured as the first one to run after the scenario state is `started`.

**Additional context:** In our case, we have an API that we poll when a test user's session is being created. When the session is still being created, the response of that API will be:

```json
{"id":"89f93e1f-28c6-452d-b102-ee4c74252de4","processing":true}
```

Once the session has been created, a new request to that endpoint will return the following:
```json
{"id":"89f93e1f-28c6-452d-b102-ee4c74252de4","processing":false, "username": "test_username", "password": "test_password"}
```

We've recorded this scenario, and what's puzzling us is that the _last_ request has the following configuration:

```json
"scenarioName": "scenario-1-demo-sessions-bf0b9386-ee34-487a-a9b0-645664cb4a77",
"requiredScenarioState": "Started",
"newScenarioState": "scenario-1-demo-sessions-bf0b9386-ee34-487a-a9b0-645664cb4a77-2"
```
In other words, the request/response mapping that occurred _last_ during record is being placed as the _first_ mapping in the scenario.

Aside from being able to tell that it is the last request's response from the fact that the body has `processing: false`, the `Date` header in the response also tells the same story. On the last response (but incorrectly first in the scenario), the `Date` is `Thu, 07 Sep 2023 16:06:47 GMT`, but the FIRST response (incorrectly _last_ in the scenario) has a `Date` of `Thu, 07 Sep 2023 16:06:28 GMT` (19 seconds _prior_ to the response being played back first).

### Reproduction steps

This should be easily reproducible using the `Date` header as described in the **Proposal** section above. In addition to our enterprise project, I was able to reproduce this with the sample project [here](https://jsonplaceholder.typicode.com/) which was originally created to reproduce https://github.com/wiremock/wiremock/issues/2361.

**Steps:**

1. Start up a wiremock server
2. Start recording with a `POST` to the Admin API `/recordings/start` endpoint with a body like:
```json
{
  "targetBaseUrl" : "https://jsonplaceholder.typicode.com",
  "persist" : true,
  "repeatsAsScenarios" : true
}
```
3. Use `curl` against the wiremock server to `GET` `http://localhost:<port>/todos/1` **more than one time.** Doing so will create a scenario
4. Stop recording via `/recordings/stop` Admin API endpoint
5. Hit the `/scenarios` Admin API endpoint to get all scenarios
6. Note the `Date` header of the FIRST mapping in the scenario (i.e the one with `requiredScenarioState` as `Started`) and see that it is _after_ the LAST mapping in the scenario (i.e the one that does not have a `newScenarioState`.

**Comment by adamwojszczyk** [comment]
I've just started using Wiremock to proxy requests to other services and record mappings for playback and I noticed that insertionIndex is in reverse order. For example there are 5 requests. Request 1 has index 5 and Request 5 has index 1. Is it by design? Can I save mappings by myself with reserved index without breaking playback? What I want to achieve is to have mappings files' names starting with request number to intuitively go through history from file 1 not for example 15.
Of course I set .filenameTemplate("{{{insertionIndex}}}.json")
wiremock 3.0.3

**Comment by oleg-nenashev** [comment]
Thanks for the report! Most likely it is a regression in the recent versions where we changed a lot around collections

**Comment by btrautmann** [comment]
> Thanks for the report! Most likely it is a regression in the recent versions where we changed a lot around collections

Thanks @oleg-nenashev. Do you know if this is something that'll get prioritized? Not trying to rush, just trying to understand team priorities so we can figure out a workaround (might mean we just don't run that specific test for now)

**Comment by adamwojszczyk** [comment]
With Wiremock 3.1.0 I still observe revers order of **insertionIndex**. Is it something to fix or it works by design?

**Comment by tomakehurst** [comment]
@adamwojszczyk can you share the details of how to replicate what you're seeing?

**Comment by adamwojszczyk** [comment]
Here is my configuration. I make several call to service1 through wiremock and snapshot stubs. insertionIndex in file name and in the content of a stub are the same and in the reversed order.

```
new WireMockServer(
            WireMockConfiguration.options()
                .port(wiremockPort)
                .withRootDirectory(testDir)
                .filenameTemplate("{{{insertionIndex}}}-{{{name}}}.json")
        );
        
        wiremockServer.stubFor(
        any(WireMock.urlMatching("/service1.*"))
            .willReturn(aResponse().proxiedFrom(usgEndpoint).withProxyUrlPrefixToRemove("/service1")));
            
            calls to service1....
            
            wiremockServer.snapshotRecord(WireMock.recordSpec());
```

**Comment by adamwojszczyk** [comment]
When I use `wiremockServer.startRecording()` insertionIndexes are correct, but still don't start from 1 but for example from 3 when I have 3 services defined as above.

**Comment by adamwojszczyk** [comment]
Also when I have for example 3 services defined `insertionIndex` starts from 3.

**Comment by tomakehurst** [comment]
OK, the insertion index does indeed reflect the fact that the scenarios issue was fixed by reversing the stub order when snapshotting. So insertion order doesn't reflect the order in which the scenario is played back, although the scenario plays back correctly regardless of the index value because it's the scenario state fields that determine this.

Is the index significant to the correct functioning of your tests, or is it just that it looks a bit confusing?

**Comment by adamwojszczyk** [comment]
It's confusing. It worked like that before the scenarios' fix. I would like to use recordings as a way to find out what is going on in test cases. Could I save stubs with proper indexing manually? Will it affect scenarios? For plain recording I think the order is also reversed it's not only snapshotting issue.
