### ISSUE TITLE
error: could not compile `wiremock` 

### ISSUE THREAD

**Issue by carrycooldude** [wiremock/wiremock#2369]
### Proposal

error[E0658]: use of unstable library feature 'pin_macro'
   --> /home/kartikey/.cargo/registry/src/github.com-1ecc6299db9ec823/wiremock-0.5.19/src/mock_server/bare_server.rs:247:32
    |
247 |         let mut notification = pin!(notify.notified());
    |                                ^^^
    |
    = note: see issue #93178 <https://github.com/rust-lang/rust/issues/93178> for more information

    Checking fake v2.8.0
error[E0658]: use of unstable library feature 'pin_macro'
 --> /home/kartikey/.cargo/registry/src/github.com-1ecc6299db9ec823/wiremock-0.5.19/src/mock_server/bare_server.rs:6:5
  |
6 | use std::pin::pin;
  |     ^^^^^^^^^^^^^
  |
  = note: see issue #93178 <https://github.com/rust-lang/rust/issues/93178> for more information

### Reproduction steps

```
cargo clippy --all-features --all-targets
```
While running this cmd on this project
https://github.com/carrycooldude/hyperswitch.git

**Comment by oleg-nenashev** [comment]
Hello @carrycooldude . I am pretty sure this is for https://github.com/LukeMathWalker/wiremock-rs from @LukeMathWalker. I cannot transfer the issue between GitHub organizations, and I suggest creating a new one

**Comment by carrycooldude** [comment]
> Hello @carrycooldude . I am pretty sure this is for https://github.com/LukeMathWalker/wiremock-rs from @LukeMathWalker. I cannot transfer the issue between GitHub organizations, and I suggest creating a new one

Thanks for letting me know
