### ISSUE TITLE
Move Webhooks extension into the core

### ISSUE THREAD

**Issue by tomakehurst** [wiremock/wiremock#2373]
### Proposal

Due mostly to side effects of JAR shading the webhooks extension has proved brittle and prone to breaking in ways that are hard to detect in the core test suite.

The extension itself is small and doesn't use any dependencies that aren't already present in WireMock. Given these points and its popularity it seems sensible to move it into the core.

The following changes would also simplify and improve the dev experience:
* Enable it by default (since it's activated via specific data on individual stubs this shouldn't be an issue for non-webhook users)
* Add `WebhookTransformer` as a new extension type so that it can be applied without having to new up the extension yourself.
* Make it implement the new `ServeEventListener` interface in addition the the legacy `PostServeAction` so that it can be activated either way.
* Add sub-events containing the details of the request and response made by the extension (note, this might be tricky when we're using external `Stores` implementations since webhooks are triggered asynchronously and could thus generate the sub-event after completion of the main response and thus the last point at which the serve event is saved).

**Comment by oleg-nenashev** [comment]
Fine with me

**Comment by oleg-nenashev** [comment]
@tomakehurst Just to double check, do we want to move it now before the WireMock 3 announcements? I would guess so, and I am rather +1 even if this is a formally breaking change for those who depend on the WireMock Webhook Extension artifact and will need to adapt their code

**Comment by tomakehurst** [comment]
Yeah, it's still broken in some contexts so I'm happy for it to be a technically breaking change if it fixes the issue once and for all.

I've nearly finished implementing this so let's leave the announcement until Friday, then hopefully this will be done and included.

**Comment by tomakehurst** [comment]
Completed in 81dd277ebc45ddfb485d71544d9825ebdead19af
