### ISSUE TITLE
gRPC extension

### ISSUE THREAD

**Issue by tomakehurst** [wiremock/wiremock#2383]
### Proposal

An extension that supports mocking gRPC APIs.

Proposed characteristics:
* Maps proto messages to/from JSON bodies so that JSON matching and response templating can be used with JSON based APIs.
* For methods that support streaming requests and unary responses the response will be sent as soon as a single request message matches a stub.
What happens if we don't match anything?
* For methods that support streaming requests and streaming responses a response message will be sent for each request message that matches a stub. The response stream will be closed when the request stream is closed, and if no stubs match this will result in an empty response stream.

**Comment by oleg-nenashev** [comment]
It duplicates https://github.com/wiremock/ecosystem/issues/14 from our
roadmap

**Comment by tomakehurst** [comment]
Let's make this the main issue then. People are more likely to find this one I think.

**Comment by tomakehurst** [comment]
Work in progress for those interested in how the extension and its DSL is shaping up:
https://github.com/wiremock/wiremock/blob/grpc-spike/wiremock-grpc-extension/src/test/java/org/wiremock/grpc/GrpcAcceptanceTest.java#L39

**Comment by oleg-nenashev** [comment]
I will move https://github.com/wiremock/ecosystem/issues/14 to preview
