### ISSUE TITLE
Gradle replaces SLF4J-API 1.7.36 with 2.0.7, causing warning about no providers in wiremock-standalone

### ISSUE THREAD

**Issue by tpearsonbray** [wiremock/wiremock#2415]
### Proposal

WireMock depends on `slf4j-api:1.7.36` and WireMock standalone depends on `slf4j-noop:1.7.36` 

As WireMock dependencies use other versions of`slf4j-api`, Gradle resolves the versions to the latest:
Partial output of `gradlew dependencies`
![Partial output of gradlew dependencies](https://github.com/wiremock/wiremock/assets/112588886/fb71fd3f-75b8-4ffd-818e-9cf4e1cfd310)

It does not change the version of `slf4j-noop`, resulting in a mismatch and a warning that there are no providers since SLF4J 2+ expects providers to be loaded via SPI. 

![image](https://github.com/wiremock/wiremock/assets/112588886/24b633b3-148f-48fe-8472-c100db0a3379)

The warning can be resolved specifying the provider `wiremock.org.slf4j.helpers.NOP_FallbackServiceProvider` in `META-INF/services/wiremock.org.slf4j.spi.SLF4JServiceProvider`. 

### Reproduction steps

1. Create a project with `wiremock-standalone` as a test dependency
2. Start a WireMock server in the test
3. Observe the SLF4J warning

### References

https://github.com/wiremock/wiremock/issues/1964 

A portion of `wiremock.org.slf4j.LoggerFactory` in `wiremock-standalone` 3.2.0 showing the URL constant for the ignoredBindings warning: 
![image](https://github.com/wiremock/wiremock/assets/112588886/6090d4ac-f21e-466e-bdd3-0a3cf88302c9)

**Comment by oleg-nenashev** [comment]
Thanks for reporting!

**Comment by Xabibax** [comment]
I did it in #2449
