### ISSUE TITLE
The urlPathTemplate cannot match the query parameter.

### ISSUE THREAD

**Issue by czwtest** [wiremock/wiremock#2422]
### Proposal

I created a stub using the urlPathTemplate: “/contract/app/{pid}/api/{id}/overview”. When I made a request using the path: “/contract/app/1699603961400320001/api/1709863759148662785/overview”, the response was successful. However, when I added a query parameter and used the path: “/contract/app/1699603961400320001/api/1709863759148662785/overview?arg=2” to request, an error occurred with the message: “Path parameter does not match”.

### Reproduction steps

first: the response was successful.
url path:/contract/app/1699603961400320001/api/1709863759148662785/overview
The stub:
{
  "id" : "b290dbf6-bed1-435a-b6d9-e4aac8f6035d",
  "request" : {
    "urlPathTemplate" : "/contract/app/{pid}/api/{id}/overview",
    "method" : "GET",
    "headers" : {
      "accept" : {
        "equalTo" : "application/json",
        "caseInsensitive" : true
      }
    },
    "pathParameters" : {
      "pid" : {
        "equalTo" : "1699603961400320001",
        "caseInsensitive" : true
      },
      "id" : {
        "equalTo" : "1709863759148662785",
        "caseInsensitive" : true
      }
    },
    "queryParameters" : {
      "arg" : {
        "equalTo" : "2",
        "caseInsensitive" : true
      }
    }
  },
  "response" : {
    "status" : 200,
    "body" : "{\r\n    \"code\": 300,\r\n    \"data\": true,\r\n    \"msg\": \"success\"\r\n}",
    "headers" : {
      "content-type" : "application/json"
    }
  },
  "uuid" : "b290dbf6-bed1-435a-b6d9-e4aac8f6035d",
  "persistent" : true,
  "insertionIndex" : 1
}
second: an error occurred with the message: “Path parameter does not match”:
url path:/contract/app/1699603961400320001/api/1709863759148662785/overview?arg=2
the stub:
{
  "id" : "b290dbf6-bed1-435a-b6d9-e4aac8f6035d",
  "request" : {
    "urlPathTemplate" : "/contract/app/{pid}/api/{id}/overview",
    "method" : "GET",
    "headers" : {
      "accept" : {
        "equalTo" : "application/json",
        "caseInsensitive" : true
      }
    },
    "pathParameters" : {
      "pid" : {
        "equalTo" : "1699603961400320001",
        "caseInsensitive" : true
      },
      "id" : {
        "equalTo" : "1709863759148662785",
        "caseInsensitive" : true
      }
    },
  },
  "response" : {
    "status" : 200,
    "body" : "{\r\n    \"code\": 300,\r\n    \"data\": true,\r\n    \"msg\": \"success\"\r\n}",
    "headers" : {
      "content-type" : "application/json"
    }
  },
  "uuid" : "b290dbf6-bed1-435a-b6d9-e4aac8f6035d",
  "persistent" : true,
  "insertionIndex" : 1
}

The error:
![image](https://github.com/wiremock/wiremock/assets/31637511/319bfdd9-ea6d-4d14-9554-2b24205009b0)

**Comment by oleg-nenashev** [comment]
I think it is quite as-designed, but not 100% sure what should be the default behavior (now it is same as `absent` but should be `any` matcher which seems to be missing for form parameters at all). I also created https://github.com/wiremock/wiremock.org/issues/206 to have such a case explicitly documented
