### ISSUE TITLE
Use Optional.orElseGet() when feasible

### ISSUE THREAD

**Issue by picimako** [wiremock/wiremock#2442]
### Proposal

There are a couple of places in the WireMock codebase that uses `Optional.orElse()`, but the value passed in could be evaluated lazily. For those occurrences I think `Optional.orElseGet()` could be used.

To name a few locations:
- [RequestPattern](https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/matching/RequestPattern.java#L267)
- [WireMockExtension](https://github.com/wiremock/wiremock/blob/master/src/main/java/com/github/tomakehurst/wiremock/junit5/WireMockExtension.java#L199)

If you greenlight this issue, I'll gladly open a PR for it.

**Comment by oleg-nenashev** [comment]
🟢 @picimako

**Comment by picimako** [comment]
Closing as this has already been released in WireMock 3.3.1.
