### ISSUE TITLE
Support for HTTP/2

### ISSUE THREAD

**Issue by Lolf1010** [wiremock/wiremock#2459]
### Proposal

Hey all,

if this is not the correct type of issue, please feel free to convert it to the correct type.

according to Issue #362, as i unterstand it, HTTP/2 should be supported by Wiremock. Is that the case?
I am asking because my tests work fine if i use 1.1 in a java.net.http.HTTPClient but when i switch to 2 it breaks.
Are changes in the Wiremock-Configuration necessary when changing the HTTP-Version ?
If HTTP/2 is currently not supported feel free to close this issue ;)
Thx.

**Configuration**
- Version = 3.2.0 (Standalone)
- Junit 5.9.3
- Java 17
- no known jetty oder similar Dependency

**Expceptions**
I am getting different exceptions
- java.io.IOException: Can't get stream 1: java.io.EOFException: EOF reached while reading
- java.io.IOException: Can't get stream 1: java.io.EOFException: /127.0.0.1:55690: GOAWAY received
- java.io.IOException: Received RST_STREAM: Stream cancelled

### Reproduction steps

HTTP-Client
```java
HTTPClient client = HTTPClient.newBuilder().version(HTTP_2).cookieHandler(...).build()
client.send(request, responseBodyHandler);
```

Test
```java
@WireMockTest
public class Testclass {

   @Test
   public void test(WireMockRuntimeInfo info) {
      WireMock.stubFor(put(urlEqualTo(...)).withRequestBody(...).willReturn(...));

     // create client and send request
     // Exception occurs
   }
}
```

**Comment by bylidev** [comment]
If you use test containers, this will work 😄 

```
  new WireMockContainer(WIREMOCK_CONTAINER_IMAGE)
             .withCliArg("--disable-http2-plain")
```

**Comment by vicaba** [comment]
Hello @bylidev , I am currently setting some up some integration tests and I see the protocol used to communicate is HTPP 1.1.
I am assessing if it is a wiremock issue. As per you answer:

> If you use test containers, this will work 😄
> 
> ```
>   new WireMockContainer(WIREMOCK_CONTAINER_IMAGE)
>              .withCliArg("--disable-http2-plain")
> ```

This `.withCliArg("--disable-http2-plain")` should tell Wiremock to use HTTP 2? It doesn't change anything for me (and I am trying to figure out if it is wrong Wiremock config or wrong HTTP client config)
(Also, the name of the argument seems misleading, hence my doubts).

Thanks.
