### ISSUE TITLE
@WireMockTest annotation does not work on abstact classes

### ISSUE THREAD

**Issue by kkocel** [wiremock/wiremock#2499]
### Proposal

I want to propose that `@WireMockTest`, when added to abstract/base classes, should affect subclasses as well.

In contrast, `@SpringBootTest` can be used on abstract classes, and all inheriting classes are treated as Spring Boot tests.

### Reproduction steps

Abstract class:
```java
@SpringBootTest
@WireMockTest(proxyMode = true)
public abstract class SpringBootWiremockTest {}
```

Actual test:
```java
class MyTest extends SpringBootWiremockTest {
}
```

**Comment by simakmi** [comment]
Faced the same issue(
