### ISSUE TITLE
Invalid JSON input on handlebars is not reported properly.

### ISSUE THREAD

**Issue by dirkbolte** [wiremock/wiremock#2546]
### Proposal

See thread https://wiremock-community.slack.com/archives/C03N1E6HFPY/p1703250590706619 .

When an input JSON is empty, this results in a `HandlebarsException`, which is converted into the following response.

```
{
    "cause1": "java.lang.IllegalArgumentException: json string can not be null or empty",
    "servlet": "com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet-4af6839c",
    "cause0": "com.github.jknack.handlebars.HandlebarsException: inline@35c3c400:1:2: java.lang.IllegalArgumentException: json string can not be null or empty\n    inline@35c3c400:1:2",
    "message": "com.github.jknack.handlebars.HandlebarsException: inline@35c3c400:1:2: java.lang.IllegalArgumentException: json string can not be null or empty\n    inline@35c3c400:1:2",
    "url": "/test",
    "status": "500"
}
```

I would have expected https://github.com/wiremock/wiremock/blob/b3874f041baad7c7466a11dfabc5125f802799b4/src/main/java/com/github/tomakehurst/wiremock/extension/responsetemplating/helpers/HandlebarsJsonPathHelper.java#L55 to have caught the issue but it seems like the actual exception is different (breakpoint isn't hit).

### Reproduction steps

- Create response templating which uses handlebars (e.g. a `POST`)
- add handlebars code: `{{jsonPath (defaultIfEmpty request.body '{}') '$.doesNotExist' }}`
- do a request without a body

Expected behavior:
- `handleError` is executed.

Actual: 
- the error is encoded in the response.

### References

See thread https://wiremock-community.slack.com/archives/C03N1E6HFPY/p1703250590706619 .

**Comment by dirkbolte** [comment]
Found that the code already had some precautions for a `null` body - would suggest to use the same approach for empty string.

**Comment by G-Basak** [comment]
@dirkbolte Is this issue good to close?

**Comment by dirkbolte** [comment]
Yes
