### ISSUE TITLE
gradle-wrapper.jar is inconsistent with current gradle version.

### ISSUE THREAD

**Issue by HappyHacker123** [wiremock/wiremock#2572]
### Summary

# Problem Description

Currently wiremock is using gradle 8.0.1 as mentioned in gradle-wrapper.properties and the checksum of current wrapper.jar is 33ad4583fd7ee156f533778736fa1b4940bd83b433934d1cc4e9f608e99a6a89. However, as can be seen from official doc https://gradle.org/release-checksums/, the expected checksum of wrapper.jar 8.0.1 should be 91941f522fbfd4431cf57e445fc3d5200c85f957bda2de5251353cf11174f4b5. The inconsistency means that the wrapper.jar is stale and should be updated.

# Possible Solution 
As mentioned in gradle official document https://docs.gradle.org/current/userguide/gradle_wrapper.html#sec:upgrading_wrapper, you will need to run the wrapper task a second time to make sure the wrapper.jar is updated. You can run the below command in the root project. Automatically the wrapper scripts will be generated by gradle.
```
bash gradlew wrapper
```

**Comment by jamietanna** [comment]
Thanks for reporting this, @HappyHacker123! Would you like to raise a PR to resolve this, or happy if we sort this internally?

**Comment by HappyHacker123** [comment]
> Thanks for reporting this, @HappyHacker123! Would you like to raise a PR to resolve this, or happy if we sort this internally?

Thanks for your reply. I'm willing to raise a pr :)
