### ISSUE TITLE
Is it feasible to set the level of SubEvents or to make them inactive?

### ISSUE THREAD

**Issue by Khalith-Basha** [wiremock/wiremock#2606]
It would be convenient to be able to fully disable SubEvents or adjust their level. We receive a lot of SubEvents regarding unmatched matchers as a result of unmatched matchers whenever we receive a lot of requests for a generic response. Unfortunately, when the server requests service event journals, it runs out of memory due to this information.

![image](https://github.com/wiremock/wiremock/assets/3997737/dbb47aea-9b05-4248-bf72-c5e05dfba27a)

**Comment by tomakehurst** [comment]
Not exactly what you asked for, but the above PR is a quick fix that's releasable under a patch version bump and will hopefully address the issue you're seeing.
