### ISSUE TITLE
Broken link in /Documentation / Using WireMock with Spring Boot

### ISSUE THREAD

**Issue by kisinad** [wiremock/wiremock#2675]
### Summary

The link to `https://wiremock.org/docs/configurations/jvm` on the` /Documentation / Using WireMock with Spring Boot` page is currently broken. When attempting to access the link, I receive. Page Not Found

**Comment by leeturner** [comment]
Thanks for reporting the issue.  This will be fixed when this PR is deployed - https://github.com/wiremock/wiremock.org/pull/277
