### ISSUE TITLE
Introduce a GUI for open source

### ISSUE THREAD

**Issue by dniald** [wiremock/wiremock#2714]
### Proposal

I've been using WireMock for a while now, and while it's an amazing tool, I think we can make it even better. How? By adding a Graphical User Interface (GUI)!

I'm excited about the idea of adding a Graphical User Interface (GUI) to WireMock Open Source! With a GUI, developers can easily create and manage stubs and expectations, visualize requests and responses for debugging, simplify configuration, and monitor traffic in real-time. Let's work together to make WireMock more accessible and user-friendly for developers everywhere!

**Comment by leeturner** [comment]
Hi @dniald Thank you for taking the time to post.  We are really pleased that you like WireMock.  

At the moment there are quite a few WireMock GUIs out there, both commercial and open source so this isn't something we will be adding to the core.  We are keen to keep the core as lean as possible and focus on the primary use case as well as the code API and json interface.
