### ISSUE TITLE
Possible memory leak ?

### ISSUE THREAD

**Issue by frgirard** [wiremock/wiremock#2731]
### Proposal

Hello, it seems I noticed a memory leak in wiremock-standalone release.
I first saw this leak with version 3.4.5, I updated to 3.5.4 and it seems to be still here.
![leak](https://github.com/wiremock/wiremock/assets/104365647/dbf64d7d-5407-4d66-9433-16fa1e4072a4)

In about 3 to 4 days, wiremock becomes unresponsive and stop working. The JVM has to be restarted.

### Reproduction steps

Nothing special.

**Comment by leeturner** [comment]
Hi, many thanks for the issue.  Could you please give us a little more information about how you are running WireMock standalone:

* What startup parameters are you using 
* Are you constraining the request log in any way
* Are you using a `health` endpoint for WireMock in your environment and if so is that via a stub you have created or the official admin health endpoint?

If you could provide the above information it will hopefully help us figure out what is happening

**Comment by frgirard** [comment]
Startup parameters:

`java -XX:+UseSerialGC -Xms512m -Xmx512m -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=64M -XX:CompressedClassSpaceSize=16M -XX:+DisableExplicitGC -cp wiremock-standalonejar:cube-wiremock-extension.jar wiremock.Run --extensions="com.decathlon.transformers.MemberIdentity","com.decathlon.transformers.MemberLogin" --port 8080 --no-request-journal --async-response-enabled --disable-request-logging --global-response-templating --permitted-system-keys="cubemock.*,ValidationBEAccount.*" `

Health endpoint not used at the moment (will be).

**Comment by frgirard** [comment]
![image](https://github.com/wiremock/wiremock/assets/104365647/91c83329-0042-41a9-ace3-abeeefb6b86f)

![image](https://github.com/wiremock/wiremock/assets/104365647/834b6268-24bb-4788-af31-33e0c65358a3)

**Comment by leeturner** [comment]
Many thanks for the information.  Could I just ask, what stub features they’re using in your tests?  I might be useful to know in case it’s a specific matcher or helper (or other feature) that’s leaking

**Comment by frgirard** [comment]
We use some custom transformers. But I couldn't see any related class in the _heap dump_.

**Comment by leeturner** [comment]
What about any matchers that you might be using ?

**Comment by frgirard** [comment]
We're still investigating, but to me it seems that a cache fills up the heap (I can see HTTP or JSON responses in it)
![image](https://github.com/wiremock/wiremock/assets/104365647/5a1525ef-7f27-4f8d-bd5e-09699792aa59)

**Comment by frgirard** [comment]
Maybe not a leak. We'll try to add "--max-template-cache-entries" to the command line.

**Comment by leeturner** [comment]
Interesting.  Many thanks for the investigation you are doing

**Comment by frgirard** [comment]
--max-template-cache-entries: Set the maximum number of compiled template fragments to cache. Only has any effect when response templating is enabled. Defaults to no limit.

The "defaults to no limit" strategy seems reckless :)

**Comment by leeturner** [comment]
Yeah, would be really interested to know if that solves your issue or just uncovers something else

**Comment by frgirard** [comment]
The leak is fixed…

![image](https://github.com/wiremock/wiremock/assets/104365647/13bb7941-725e-49d5-b4ab-0d7e3cbdac9c)

**Comment by leeturner** [comment]
That is great to hear.  I'll talk to the team about maybe defaulting `--max-template-cache-entries` to a sensible value.  Are you happy to close this issue now?

**Comment by frgirard** [comment]
Yes please.
Thank you.

**Comment by leeturner** [comment]
Closed after solution found with setting `--max-template-cache-entries`
