### ISSUE TITLE
__files created by default since v3.6.0

### ISSUE THREAD

**Issue by jkmcl** [wiremock/wiremock#2739]
### Proposal

Directory `src/test/resources/__files` does not exist in my project but I notice that WireMock is creating it automatically after upgrading to version v3.6.0.

I think this should _not_ be the default behavior.

### Reproduction steps

Create a project that uses WireMock 3.6.0 but does not use any of its API that requires the existence of `__files`. Run some test that uses WireMock and an empty `src/test/resources/__files` will be created.

### References

It seems that this undesired behavior is introduced by commit 3be4a18.

**Comment by chrisgleissner** [comment]
Same here. Until this is fixed, I am using the following work-around on a Gradle project. This effectively disables using file-based stubs as it tries to source them from `build`, but that's fine for my use case.

```
val wireMockServer = WireMockServer(options().port(0).usingFilesUnderDirectory("build"))
```
