### ISSUE TITLE
could not find helper: "jsonMerge"

### ISSUE THREAD

**Issue by philipbushnell-valtech** [wiremock/wiremock#2794]
### Proposal

The `jsonMerge` helper doesn't seem to be available in the latest version of wiremock. Following [the docs](https://docs.wiremock.io/response-templating/json/#merging-json-objects) it doesn't work:

![image](https://github.com/wiremock/wiremock/assets/78373345/f87b6e8b-2b2c-407b-a0aa-4277ea55ed58)

It might be noteworthy that I am able to use `jsonPath` and `parseJson` without issue.

### Reproduction steps

Here's my test usage (response templating works correctly without this in it):
```
{{#assign 'test1'}}{ "a": 1, "b": 2 }{{/assign}}
{{#assign 'test2'}}{ "a": 9, "c": 3 }{{/assign}}

{{jsonMerge test1 test2}}
```

Even copying the exact code from the docs produces the same result.

---

It's being run through Docker, Windows and JSON:
```
FROM wiremock/wiremock

COPY apps/wiremock/mappings/ /home/wiremock/mappings/

COPY apps/wiremock/__files/ /home/wiremock/__files/
```

![image](https://github.com/wiremock/wiremock/assets/78373345/b360c047-ab8a-43d2-8695-0aefa8c7b2e8)

---

Here's the associated mapping:
```json
{
  "priority": 1,
  "request": {
    "method": "POST",
    "url": "<redacted>",
    "bodyPatterns": [
      {
        "matchesJsonPath": {
          "expression": "<redacted>",
          "contains": "<redacted>"
        }
      }
    ]
  },
  "response": {
    "status": 200,
    "headers": {
      "X-Powered-By": "Express",
      "X-DLX-Session-ID": "4d4ab3c6-ebbf-48ea-abc0-07bf2e478ced",
      "Content-Type": "application/json; charset=utf-8",
      "Connection": "keep-alive",
      "Keep-Alive": "timeout=5",
      "ETag": "W/\"376-UBGZH3CiWeDeXgAkzX5a+tt1zTk\""
    },
    "bodyFileName": "<redacted>.json",
    "transformers": ["response-template"]
  }
}
```

**Comment by leeturner** [comment]
Hi, the docs you have linked to are the docs for [WireMock Cloud](https://www.wiremock.io/comparison).  The `jsonMerge` helper is available in the Cloud product but not the OSS product.  The docs for the OSS product are here - https://wiremock.org/docs/

**Comment by philipbushnell-valtech** [comment]
Ah my mistake. Are there any plans to support additional helpers? This one in particular will be of massive help to reduce the template size dramatically.

**Comment by leeturner** [comment]
As far as I know there are no immediate plans to support those helpers in WireMock OSS.
