### ISSUE TITLE
Reload of mappings

### ISSUE THREAD

**Issue by rabelenda** [wiremock/wiremock#28]
Are there any plans to include, or is there any existing functionality to either periodically and/or through the admin api to reload the mappings?. So whenever I add new mapping, or modify existing ones through the files within mappings folder in standalone, those changes can take place without having to restart the application.

**Comment by iamlile** [comment]
Thanks,this just i  need.

**Comment by tarekahf** [comment]
Thank you! I was looking for this feature also.
