### ISSUE TITLE
Response Template behaviour changed in 3.X version 

### ISSUE THREAD

**Issue by KHossainStream2023** [wiremock/wiremock#2816]
following mapping is not returning same result 
POST /mappings
Content-Type: [application/json]
{
  "request" : {
    "urlPath" : "/api/qp",
    "method" : "GET"
  },
  "response" : {
    "status" : 200,
    "body" : "{{ request.query }}",
    "transformers" : [ "response-template" ]
  }
}

Version 2.35.0 
----------------

> curl "http://localhost:8080/api/qp?vad=linear&id=21743558653&app=app1&output=xml" -v
> Connected to localhost (::1) port 8080
> GET /api/qp?vad=linear&id=21743558653&app=app1&output=xml HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Matched-Stub-Id: fa85c987-893d-4afb-99be-f230a48782b6
< Transfer-Encoding: chunked
< * Connection #0 to host localhost left intact
**{vad=linear, id=21743558653, app=app1, output=xml}**

Version 3.9.0 
---------------

> curl "http://localhost:8080/api/qp?vad=linear&id=21743558653&app=app1&output=xml" -v
> Connected to localhost (::1) port 8080
> GET /api/qp?vad=linear&id=21743558653&app=app1&output=xml HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Matched-Stub-Id: fa85c987-893d-4afb-99be-f230a48782b6
< Transfer-Encoding: chunked
< * Connection #0 to host localhost left intact
**{app=app1, output=xml, vad=linear, id=21743558653}**

In version 3.x original order of query params is broken

### Reproduction steps

1. Run wiremock:
  docker run -it --rm -p 8080:8080 --name wiremock wiremock/wiremock:2.35.0 --global-response-templating --verbose
2. Create mapping:
curl -X POST "http://localhost:8080/__admin/mappings" \
-H "Content-Type: application/json" \
-d '{
  "request": {
    "urlPath": "/api/qp",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "body": "{{{ request.query }}}",
    "transformers": ["response-template"]
  }
}'

3. curl "http://localhost:8080/api/qp?vad=linear&id=21743558653&app=app1&output=xml" -v

do same for wiremock:3.9.0

**Comment by tomakehurst** [comment]
Order of query parameters is undefined, and in any case this is a major version change. I suggest finding a more robust way to work with query parameters that isn't order-dependent.
