### ISSUE TITLE
headers -> hasExactly with several variants not match in request checkinf

### ISSUE THREAD

**Issue by evgenym87** [wiremock/wiremock#2831]
### Proposal

Header with several "hasExactly"->"equalTo" params will newer match.
Version 3.9.1

### Reproduction steps

If we create stub with this piece:
"headers": {
      "Accept": {
        "hasExactly": [
          {
            "equalTo": "text/plain"
          },
          {
            "equalTo": "application/json"
          },
          {
            "equalTo": "text/json"
          }
        ]
      }
Header "Accept" (and any other header) will newer match.
Accept: text/plain                                  <<<<< Header does not match

But with single "equalTo" Wiremock will work properly:
"headers": {
      "Accept": {
        "hasExactly": [
          {
            "equalTo": "text/plain"
          }
        ]
      }

**Comment by RafeArnold** [comment]
this is not a bug. the hasExactly matcher expects every value to be matched on the request.
```json
"headers": {
  "Accept": {
    "hasExactly": [
      {
        "equalTo": "text/plain"
      },
      {
        "equalTo": "application/json"
      },
      {
        "equalTo": "text/json"
      }
    ]
  }
}
```
will only match if there are three Accept headers on the request, each one matching one of the expected values. if you only want one of the expected values to be present in the Accept header for the stub to match, use
```json
"headers": {
  "Accept": {
    "or": [
      {
        "equalTo": "text/plain"
      },
      {
        "equalTo": "application/json"
      },
      {
        "equalTo": "text/json"
      }
    ]
  }
}
```
