### ISSUE TITLE
SQL Data Store Integration

### ISSUE THREAD

**Issue by x80486** [wiremock/wiremock#2879]
### Proposal

I would like to propose an enhancement to WireMock that could simplify the handling of dynamic responses by integrating support for a SQL data store. This will enable users to use a lightweight data store, such as SQLite, to retrieve data from a Relational Database Management System (RDBMS) by means of `SELECT` SQL statements, and return dynamic responses from very large datasets with minimal configuration.

The DSL would need to be _augmented_ as well to provide the actual features and integration.

**Comment by leeturner** [comment]
Hi, thank you for the issue but this isn't the kind of thing that is suitable to go in the core.  This could be done in an extension if you fancied putting something together or maybe the CSV extension might work for you - https://github.com/massamany/WireMockCsv
