### ISSUE TITLE
Not able to user Wiremock as a HTTPS Proxy server 

### ISSUE THREAD

**Issue by AnishVohra** [wiremock/wiremock#2882]
I am able to generate the wiremock.jks in windows and using the following command to start the Wiremock from Command prompt 

Command: C:\wiremock>C:\jdk-22.0.1\bin\java -cp "wiremock-standalone-3.9.1.jar;wiremock-graphql-extension-0.9.0-jar-with-dependencies.jar" wiremock.Run --extensions io.github.nilwurtz.GraphqlBodyMatcher --port 9999 --https-port 2929 --https-keystore wiremock.jks --enable-browser-proxying --trust-all-proxy-targets --verbose

After that I am using https:localhost:9091 as my proxy to fetch the Wiremock Response in chrome browser, buy getting following Error in chrome browser:  
net::ERR_PROXY_CONNECTION_FAILED

Can someone please help me resolve this issue?

**Comment by tomakehurst** [comment]
Hi @AnishVohra I suggest you head over to the Slack community to ask about this as it seems like a support issue rather than a bug.
