### ISSUE TITLE
How to use soapXPath helper to extract header entry on soap ? 

### ISSUE THREAD

**Issue by asicfr** [wiremock/wiremock#2885]
### Summary

Hi, on the following soap content : 
```
<soap:Envelope>
   <soap:Header>
      <wsa:From>
         <wsa:Address>TEST_J</wsa:Address>
      </wsa:From>
      <wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
      <wsa:Action>urn:ServiceToto:2:creerWorkflow</wsa:Action>
      <wsa:MessageID>urn:uuid:9e4275e3-c7cd-445f-8506-1e8048dd9689</wsa:MessageID>
   </soap:Header>
   <soap:Body>
   </soap:Body>
</soap:Envelope>
```
How can i use the soapXPath helper to extract the message id value ? 
SoapXPath helper seems to be usable only on body part.
How can i do that please ? 

Thx

**Comment by leeturner** [comment]
Hi, the `soapXPath` helper is just a specialised version of the `xpath` helper.  As you mention, the `soapXpath` helper targets the body part.  Have you tried using the `xpath` helper to target the message id in the Header ?

**Comment by asicfr** [comment]
Hi, 
I have also try xpath like that : 
```
{{xPath request '/*/soap:Header/wsa:MessageID/text()'}}
```
with request example : 
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:v2="http://www.cnamts.fr/SUPPORT/ServiceMaestro/v2">
   <soap:Header xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:ctx="urn:siram:contexteSIR">
      <wsa:From>
         <wsa:Address>abcd</wsa:Address>
      </wsa:From>
      <wsa:To>http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
      <wsa:Action>urn:Service:2:creerInstancesWorkflow</wsa:Action>
      <wsa:MessageID>urn:uuid:9e4275e3-c7cd-445f-8506-1e8048dd9689</wsa:MessageID>
   </soap:Header>
   <soap:Body>
      <v2:creerInstancesWorkflowRequestElement>
      </v2:creerInstancesWorkflowRequestElement>
   </soap:Body>
</soap:Envelope>
```
but i failed : 
[ERROR: com.github.tomakehurst.wiremock.extension.responsetemplating.RequestTemplateModel@6e69d7f5 is not valid XML]

Using the xpath and soap example is valide on http://xpather.com/.

**Comment by leeturner** [comment]
The `request` element is the whole request (url, query params etc). You might want to try `request.body`

**Comment by asicfr** [comment]
Thanks,
With request.body, i got empty value for {{xPath request.body '/*/soap:Header/wsa:MessageID/text()'}}


REQUEST : 
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:v2="http://www.cnamts.fr/SUPPORT/ServiceMaestro/v2">
<soap:Header xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:ctx="urn:siram:contexteSIR">
<wsa:MessageID>urn:uuid:9e4275e3-c7cd-445f-8506-1e8048dd9689</wsa:MessageID></soap:Header>
   <soap:Body>
   ...
   </soap:Body>
</soap:Envelope>


TEMPLATE WIREMOCK : 
{
  "mappings": [
  {
    "request": {
      "method": "POST",
      "url": "/wkflj/services/Maestro-v2",
      "bodyPatterns": [
        { "and": [{"contains": "Error500"}, {"contains": "forcerModifierDateExpirationInstancesSequences"}]}
      ],
      "headers": { "partition": { "contains": "BACH" } }
    },
    "response": {
      "statusMessage": "forcerModifierDateExpirationInstancesSequences sur BACH avec reponse en moins de 800ms",
      "body": "<soap:Envelope> ... <RelatesTo>{{xPath request.body '/*/soap:Header/wsa:MessageID/text()'}}</RelatesTo> ... </soap:Envelope>"
    }
  }
  ...
}

RESPONSE WIREMOCK :
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
   <soap:Header>
  ...
      <RelatesTo xmlns="http://www.w3.org/2005/08/addressing"/>
  ...
</soap:Envelope>


WIREMOCK LAUNCH :
WireMockServer wireMockServer = new WireMockServer(
    options()
      .notifier(new ConsoleNotifier(true))
      .asynchronousResponseEnabled(true)
      .asynchronousResponseThreads(5)
      .templatingEnabled(true)
      .globalTemplating(true)
      .port(8090)
      .usingFilesUnderClasspath("stubs")
);

**Comment by asicfr** [comment]
I found solution with : {{xPath request.body '//MessageID/text()'}}

**Comment by asicfr** [comment]
thanks for your help

**Comment by leeturner** [comment]
Great news
