### ISSUE TITLE
Upgrade of GraphQL libs to the latest

### ISSUE THREAD

**Issue by miguelautoentry** [wiremock/wiremock#2899]
### Summary

GraphQl is at 8.2.1 however Wiremock.net brings transitively the version 7.5. This is halting our upgrade of graphql

**Comment by leeturner** [comment]
Hi, you might get a faster reponse if you post this issue on the WireMock.Net repo.  It isn't officially part of the WireMock github org so we don't control dependencies in that project - https://github.com/WireMock-Net/WireMock.Net
