### ISSUE TITLE
Request and response with variables

### ISSUE THREAD

**Issue by afalmeida** [wiremock/wiremock#368]
Hi,
My scenario soap, i will like to use wiremock to response xml soap with variables and response dynamic.
for example in mappings:

```
 {
"request": {
    "method": "POST",
    "url": "/order",
 `------capture` variable id of request `xml??????`
},
"response": {
        "status": 200,
             "bodyFileName":/order/id.xml, # ------response xml of variable id------  
    "headers": {
        "Content-Type": "text/xml"
    }
}
 }
```

example request:

```
<customer>
      <id>5959</id>
</customer>
```

example response:
----5959.xml

```
<customer>
    <id>5959</id>
    <name>XPTO</name>
    </customer>
</customer>
```

Can i use this scenario in wiremock, capturing id of customer and response this id of customer to xml?

Thanks!

**Comment by EugeneAbramchuk** [comment]
@afalmeida There are two ways to achieve this: either extend the Wiremock functionality (this is what a guy in my company did, see https://github.com/wirecardqa/wiremock) or upgrade to the latest version (2.0+) to use transforms - they basically marshall a request into an object and you can manipulate data however you want.

**Comment by tomakehurst** [comment]
This use case (setting the body file name based on request data) is now covered by response templating.
