### ISSUE TITLE
[Question] Use GET request parameters in response?

### ISSUE THREAD

**Issue by illaz** [wiremock/wiremock#38]
Hi, 

I want to use WireMock to mock the backend for my app.
Just a simple question: Is it possible to use parameter values of my get request in my response?

Example:
If I send a request like 

``` java
"/api/events\\?date=*"
```

 I would like to response a JSON like:

``` json
{
   "events":{
      "event":{
         "name":"event1",
         "date":"[date]"
      },
      "event":{
         "name":"event2",
         "date":"[date+1]"
      },
      "event":{
         "name":"event3",
         "date":"[date+2]"
      }
```

[date] should be replaced by the value from the request.
Is this possible using WireMock?

Thanks for the great tool and your answer ;)

Yours sincerely
Illaz

**Comment by mendlik** [comment]
Do you plan to include this feature in wiremock 2.0?

**Comment by tomakehurst** [comment]
You can already do it by implementing a response transformer extension, albeit with a little work.

I'm considering some options here - perhaps extensions that ship with WireMock but aren't activated by default to e.g. execute Javascript or template the response. Trying to figure out how to do it without adding too much bloat.

**Comment by mendlik** [comment]
Thanks for quick update. I would appreciate another comment on this issue when you figure it out.

**Comment by tomakehurst** [comment]
I'll do my best to remember :-)

Which approach are you more interested in: scripted or templated?

**Comment by mendlik** [comment]
Thanks for goodwill ;-)

Both approaches are interesting. Could you give a basic example of each of them?
Scenario is simple. Lets reuse a json object property from request body in the response.

**Comment by tomakehurst** [comment]
I was thinking of adding an extension that called a user-supplied Javascript function to determine the response e.g.
```javascript
// Copy the request body into the response body
function transformResponse(request, responseBuilder) {
  responseBuilder.body(request.body);
}
```

**Comment by tomakehurst** [comment]
Additionally there's the option of a really basic templating engine (e.g. StringTemplate) so that you can replace properties:

```
{
  "myHeaderValue": '$$request.headers.X-My-Header$$'
}
```

**Comment by mendlik** [comment]
IMHO the second option is much easier/better.

**Comment by mendlik** [comment]
In most cases I would go with the second option. I believe that first one would be useful in some edge cases.

**Comment by tomakehurst** [comment]
I like the 1st one because a) there's already a JS engine available in the JVM, and b) JSON is easy in JS.

But the 2nd is probably easiest when you just want to inject one or two values, which might be the majority case.

**Comment by mendlik** [comment]
A "real life" example. In my team we have an agreement that every successful POST request will result in a 201 response with a `Location` header and body that will contain created entity. In most cases the response body is similar to the request body but enriched with few fields (like an id). 

In this case perfect solution would be to inherit request body and add missing fields.

**Comment by tomakehurst** [comment]
OK, thanks for the input. Will consider that when I get round to doing this.
