### ISSUE TITLE
Apache HttpClient + WireMock

### ISSUE THREAD

**Issue by maybeec** [wiremock/wiremock#41]
Hi,

I have observed strange behavior when accessing a mocked server instance of WireMock with the Apache HttpClient.
When I debug the test, and go to the mocked server address in my browser, I got the expected response. However accessing the same address with the Apache HttpClient leads to a 404 response.

Necessary Information about the Test (not the whole test, only WireMock related configurations):

``` Java
 @RunWith(SpringJUnit4ClassRunner.class)
 public class Test {

    @Rule
    public WireMockRule wireMockRule = new WireMockRule(9999);

    @Before
    public void reset() {
        WireMock.reset();
    }

    @Test
    public void test() {
        String request = "Any Request";
        stubFor(get(urlEqualTo("/")).willReturn(aResponse().withStatus(200).withBody(response.getBytes())));

        verify(postRequestedFor(urlEqualTo("/"))
            .withHeader("Content-Type", equalTo("text/xml; charset=UTF-8"))
            .withHeader("SOAPAction", equalTo("")).withRequestBody(equalTo(request)));
     }
 }
```

Nice to know is, that the verification is valid. So the mock is obviously called correctly.

HttpClient-Code calling the mocked server address:

``` Java
HttpClient client = new DefaultHttpClient();
ByteArrayEntity requestEntity = new ByteArrayEntity(_requestStr_.getBytes());
requestEntity.setContentType("text/xml; charset=UTF-8");
requestEntity.setContentEncoding("UTF-8");

HttpPost httpPost = new HttpPost("http://localhost:9999");
httpPost.addHeader("SOAPAction", "");
httpPost.setEntity(requestEntity);
HttpResponse response = client.execute(httpPost);

HttpEntity entity = response.getEntity();
if (entity != null) {
    InputStream in = entity.getContent();
    try {
        System.out.print(new String(IOUtils.toByteArray(in)));
    } finally {
        in.close();
    }
}
```

Now I got the 404 Error html page from jetty, although the browser shows the right mocked response:

``` html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 404 NOT_FOUND</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /. Reason:
<pre>    NOT_FOUND</pre></p><hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>
```

Any suggestions why I got the right answer in my firefox browser and got a 404 via the Apache HttpClient? Perhaps are there any headers which are assumed to be in the request in order to let WireMock match the called URL and provide a declared response?

**Comment by sensoryorgan** [comment]
@tomakehurst  Is it possible to exclude certain query parameter while running wiremock standalone?

**Comment by cajunesque** [comment]
@tomakehurst: Hi Tom, Love your wiremock, but I have an issue which looks the same but is definitely NOT related to POST vs GET. Reduced to the basics, a simple tets pin-points the problem.

Here's my stub used in my test:
        stubFor(post(urlMatching(".*")).willReturn(aResponse().withStatus(200).withHeader("Content-Type", "text/plain").withBody("buono")));

And here's my client to read the response:
HttpPost httpRequest = new HttpPost(url);
httpRequest(new StringEntity(body, "UTF-8"));
return client.execute(httpRequest, HttpClientContext.create());

If I set up with a default client
  client = HttpClients.createDefault()
I get the expected 200 returned.

But when I use a minimal client (which i must, since I pass a connection pool to it),
   client = HttpClients.createMinimal();
it gives me a 400 error (!)

What can i do to my client or wiremock itself to get it to work with the Minimal client?
Thanks
Mark
