### ISSUE TITLE
wiremock 1.35 proxy modifies requests before calling the actual web service

### ISSUE THREAD

**Issue by bluemarble** [wiremock/wiremock#64]
I would love to use Wiremock to help unit test some client software I'm writing that calls a third-party REST service.  It appears that running the standalone jar with --proxy-all causes the header to be rewritten in a way that is not compatible with the web service I'm calling.  I need the request to be passed through to the proxy without the header changes, etc.

I'm writing to see if this is something you'd be interested in supporting, or perhaps someone in the community has a suggestion for how to get Wiremock to behave in a way that will work with this web service.  Any thoughts?

Wiremock is started like this:
`java -jar wiremock-1.35-standalone.jar --proxy-all="http://10.0.1.65" --record-mappings --verbose`

The web service calls arrive at the Wiremock proxy looking like this:

```
PUT /rest/testdata/22fb095c8fac450296bf889e8192a5b5 HTTP/1.1
Cookie: hcp-ns-auth=cmlhbHRv:89efe08fe280e438f3b3085fa94309b1
User-Agent: Jakarta Commons-HttpClient/3.0.1
Host: rialto.rialto.something-demo.somethingdomain.com
Transfer-Encoding: chunked

3
abc
0

```

However, the call to the actual web service is rewritten: it has a Content-Length instead of chunked encoding, and some of the headers are removed or changed:

```
PUT /rest/testdata/299e861855584fbfa8121af313edbff5 HTTP/1.1
Cookie: hcp-ns-auth=cmlhbHRv:89efe08fe280e438f3b3085fa94309b1
User-Agent: Jakarta Commons-HttpClient/3.0.1
Content-Length: 3
Content-Type: text/plain; charset=utf-8
Host: 10.0.1.65
Connection: Keep-Alive

abc
```

**Comment by yogamaha** [comment]
Hi @tomakehurst, Similar to the above problem I faced an issue with Proxy when the response returned by the actual service had the transfer-encoding header "chunked".

In the standalone mode, this header is lost & replaced by "content-length".
In the Webapp mode, there is no response from the service.

I resolved it for my local web app by overriding the implementation of DispatcherServlet & invoke  httpServletResponse.getOutputStream().flush() if there is "chunked" header.

All these problems are with version 1.53

**Comment by tomakehurst** [comment]
Yeah, unfortunately because it buffers responses at the moment, you always end up with a known-length byte array and hence a Content-Length header being added by Jetty.

I'll have a look at fixing this in a future version I think, as it's useful to be able to test with both.

**Comment by yogamaha** [comment]
Thanks @tomakehurst for looking into my request.
