### ISSUE TITLE
Allow access to the host/port in response template

### ISSUE THREAD

**Issue by samuel-soubeyran** [wiremock/wiremock#717]
Templating is an awesome feature but I have a use case that is currently not supported and probably wouldn't require too much work to support.

I am writing test against webservice. I first retrieve the WSDL and then make the SOAP request.
I want wiremock to serve these 2 requests and to avoid port conflict I want to be able to use dynamic port. 

Now the issue is that the wsdl reference the full url with port where the 2 request should be made. So I need to be able to figure out the right port on which wiremock is listening when serving the first request.

to make it more clear, here is an small part of my WSDL where I'd like to template the port:

```
...
<wsdl:port name="WebServiceSoap" binding="tns:WebServiceSoap">
    <soap:address location="http://localhost:{{wiremock_port}}/web/service"/>
</wsdl:port> 
...
```
My understanding is that this could be implemented in RequestTemplateModel, using request.getAbsoluteUrl(). But there might be better ways or more things that other would want to include.
If you can give me some general idea on how you'd envision this, I'd be willing to send a PR.

**Comment by samuel-soubeyran** [comment]
on a side note, I feel that url for the path is slightly misleading, AFAIK url should be the full "absolute" url include scheme, host, port, path and query (https://www.ietf.org/rfc/rfc1738.txt). Currently it seems that in the Request interface, getUrl() return the path, and getAbsoluteUrl() return the url. It's not a big deal but I'm curious about the reasons behind this choice (the logic is in WireMockHttpServletRequestAdapter).

**Comment by leeturner** [comment]
This is a pretty old enhancement request and WireMock has supported `scheme`, `host` and `port` in the request model for a little while now.  As a result I am closing this issue
