### ISSUE TITLE
WireMock @Rules in JUnit 4.11

### ISSUE THREAD

**Issue by rowanhill** [wiremock/wiremock#80]
Hi,

I took a quick look at upgrading the WireMock codebase to use JUnit 4.11 earlier, but didn't get any further than coming up with some questions, so I figured I'd get them down before I forget.

It looks like JUnit 4.11 requires `@ClassRules` to be static, but requires `@Rules` to be non-static. Unfortunately, this conflicts with the advice on the WireMock site (and the way of doing things in the `WireMockJUnitRuleTest` acceptance test) to have something like:

``` java
@ClassRule
@Rule
public static WireMockClassRule wireMockRule = new WireMockClassRule()
```

From my limited understanding of the code, it looks like the idea here is that the rule gets run as a both `ClassRule`, starting & stopping the server at the start & end of the class's tests, and as a `Rule`, resetting the server between tests (and determining which action to take by seeing if the server is running or not).

If that's correct, I don't see any way of achieving the same behaviour in JUnit 4.11: I was initially hopeful that you might be able to tell if you were executing the first or last test when called as a `@Rule` (perhaps by inspecting the `Description`), but I don't think that's possible, sadly. Of course, if anyone can point out something I've missed, that would be excellent news.

One alternative to the current scheme would be to have `WireMockRule` continue to be responsible for starting and stopping the server, either as a `@Rule` or a `@ClassRule` (as it currently is), but then provide an additional `@Rule` to call `WireMock.reset()` after each test if running `WireMockRule` as a `@ClassRule` (and deprecate WireMockClassRule).

Note also that if someone's digging around with the WireMock Rules, it may be worthwhile to make them extend ExternalResource: it might just make them a tiny bit cleaner to read.

As a slight aside, I also wonder whether it'd be worth your while having some different modules that include different versions of JUnit in order to test the behaviour of the rules in whichever versions you wish to support.

Thanks,
Rowan

**Comment by Waxolunist** [comment]
junit 4.12 is already release. Could you document that? Thx

**Comment by selangley** [comment]
This doesn't quite work in JUnit 4.12 because there is a condition in the JUnit rule validator that disallows this for MethodRule's and the existing WireMock JUnit Rule classes all implement MethodRule.

Below is the validator rule from JUnit 4.12:

`    /**
     * Requires the validated member to be non-static
     */
    private static final class MemberMustBeNonStaticOrAlsoClassRule implements RuleValidator {
        public void validate(FrameworkMember<?> member, Class<? extends Annotation> annotation, List<Throwable> errors) {
            boolean isMethodRuleMember = isMethodRule(member);
            boolean isClassRuleAnnotated = (member.getAnnotation(ClassRule.class) != null);

            // We disallow:
            //  - static MethodRule members
            //  - static @Rule annotated members
            //    - UNLESS they're also @ClassRule annotated
            // Note that MethodRule cannot be annotated with @ClassRule
            if (member.isStatic() && (isMethodRuleMember || !isClassRuleAnnotated)) {
                String message;
                if (isMethodRule(member)) {
                    message = "must not be static.";
                } else {
                    message = "must not be static or it must be annotated with @ClassRule.";
                }
                errors.add(new ValidationError(member, annotation, message));
            }
        }
    }`

**Comment by rowanhill** [comment]
Yeah, unfortunately, that's right. With WireMock as it currently stands, you have to declare the member rule and class rule separately, e.g.:

```java
    @ClassRule
    public static WireMockClassRule wireMockClassRule = new WireMockClassRule(8080);
    @Rule
    public WireMockClassRule wireMockRule = wireMockClassRule;
```

MethodRule (from JUnit 4.7) predates TestRule/ClassRule (from JUnit 4.9); I suspect the intent in WireMock is to support old versions of JUnit (i.e. 4.7 & 4.8). The cost of that is not being able to mark a single field as both rule and class rule.

@tomakehurst Perhaps this is another candidate for change in 2.x? I.e. remove the MethodRule interface from WireMockRule and WireMockClassRule?

**Comment by tomakehurst** [comment]
I think that's probably a good idea. I've been meaning to take another look at JUnit integration, so perhaps I'll try and get that into the next 2.x release.
