### ISSUE TITLE
Feature: Allow request templating

### ISSUE THREAD

**Issue by basmussen** [wiremock/wiremock#964]
Allow request templating feature which is almost similar to response templating (http://wiremock.org/docs/response-templating/) in the request part of bodyPatterns.
This allows to determined the response body dynamically using the date or other dynamic values.

`{{now offset='1 months' format='yyyyMM'}}`

For now it's fixed:
`"year_month": "201805"`

By support request templates the value can be dynamically:
`"year_month": "{{now offset='1 months' format='yyyyMM'}}"`

The full static request:
```
{
  "id" : "e1716a10-433c-3faa-bc17-cd11136fa988",
  "request" : {
    "url" : "/api/v1/values",
    "method" : "POST",
    "bodyPatterns" : [ {
      "equalToJson" : "{\n  \"query\": {\n    \"year_month\": \"201805\"\n  }\n}",
      "ignoreArrayOrder" : true,
      "ignoreExtraElements" : true
    } ]
  },
  "response" : {
    "status" : 200,
    "bodyFileName" : "body-shared-fDF51.json",
    "headers" : {
      "Content-Type" : "application/json;charset=utf-8",
      "Transfer-Encoding" : "chunked",
      "Date" : "Tue, 15 May 2018 14:54:02 GMT"
    }
  },
  "uuid" : "e1716a10-433c-3faa-bc17-cd11136fa988"
}
```

**Comment by andreroggeri** [comment]
@tomakehurst Is there any limitation here ? Maybe I could submit a PR if you're willing to accept it ! 😄

**Comment by tomakehurst** [comment]
I'm not sure I understand what this is.

I can't see how requests could be templated since they originate outside WireMock.

Can you give an example?

**Comment by andreroggeri** [comment]
Sure.

In my case I want to have a mock for the current and the previous month.
The request templating would allow the following mapping to work.

```{
    "request": {
        "urlPattern": "/sales",
        "method": "GET",
        "queryParameters": {
            "date": {
                "equalTo": "{{now format='yyyy-MM-dd'}}"
            }
        }
    },
    "response": {
        "status": 200,
        "bodyFileName": "sales-today.json",
        "headers": {
            "Content-Type": "application/json"
        }
    }
}

{
    "request": {
        "urlPattern": "/sales",
        "method": "GET",
        "queryParameters": {
            "date": {
                "equalTo": "{{now offset='-1 days' format='yyyy-MM-dd'}}"
            }
        }
    },
    "response": {
        "status": 200,
        "bodyFileName": "sales-yesterday.json",
        "headers": {
            "Content-Type": "application/json"
        }
    }
}

**Comment by siletta** [comment]
Hi @tomakehurst I was searching for the same possibility.
This is my use case: I am testing a service **A** sending to it a JSON request containing some parameters.
Once called, service **A** will create a request encoding in base64 some parameters of the one received and will call the service **B**.  **I want to check that service A is encoding these values correctly calling verify on the requests sent from A to B.**

**So if this is the request to A:**
**requestToA.json**
`{ "param1" : "one",
  "param2" : "two"
}`

**And this is the request I expect A sends to B:**
**requestToB.json**
`{ "param1" : base64("one"),
  "param2" :  base64("two")
}`

In order to test that A has encoded the parameters in the request to B I want to call the **verify** like this:

`verify(getRequestedFor(urlPathMatching("urlToB")).withRequestBody("requestToB.json")`

PS: I saw that handlebars like base64 are already supported in the Response :)

Thank you!

**Comment by PRABAREPO** [comment]
Any update on this feature ? If not could you provide Alternative solutions ?

**Comment by tomakehurst** [comment]
At present the only way to do this would be to write a custom matcher: http://wiremock.org/docs/extending-wiremock/#custom-request-matchers

I'm not keen on the idea of full-blown templating in the request matching logic (at least not as a core feature, an extension would be another matter), but I think date matching specifically would be valuable so I'm open to adding a specific matcher for this.

**Comment by PRABAREPO** [comment]
Currently, we are using standalone Wiremock  jar and inserting request/response mappings via JSON file for validation.

Could you help me with the steps on how to create custom matcher and How to use that custom matcher along with standalone jar ?

**Comment by tommck** [comment]
> Currently, we are using standalone Wiremock jar and inserting request/response mappings via JSON file for validation.
> 
> Could you help me with the steps on how to create custom matcher and How to use that custom matcher along with standalone jar ?

Did you ever solve this problem for yourself @PRABAREPO? I'm in the same situation

**Comment by tomakehurst** [comment]
I'm going to close this as the main use case seems to be dynamic date matching, for which there is now a dedicated set of matchers.
