### ISSUE TITLE
Not able to pass JSON as the query parameter

### ISSUE THREAD

**Issue by gr423** [wiremock/wiremock#978]
Hi ,
I'm passing the JSON as the query parameter.

```
String queryParam ="{\"resourceType\":\"programs\",\"resourceId\":{\"$in\":[\"GLOBAL_9073\"]}}";
wiremockClassRuleInstance.stubFor(delete(urlPathMatching("/ihs/v1/metadata")).withQueryParam("filter", WireMock.equalTo("{queryParam }"))
```

Getting the below excpetion
java.lang.IllegalArgumentException: Illegal character in query at index 24: /ihs/v1/metadata?filter={"resourceType":"programs","resourceId":{"$in":["GLOBAL_9073"]}}

Please can you help me here.

Thanks in advance,
Ramya S

**Comment by tomakehurst** [comment]
The WireMock project uses GitHub for bugs and feature requests only.

Community support is either Stackoverflow, or the Google mailing list here: https://groups.google.com/forum/#!forum/wiremock-user

I'm generally more likely to answer if you post on the mailing list.

**Comment by gr423** [comment]
Thanks Tom , sure will post on the Forum.
